### ISSUE TITLE
Add a simple mode for client-side data

### ISSUE THREAD

**Issue by lucasfurlani** [aldeed/meteor-tabular#102]
I am trying to do something like this:

There is the collection "people"  with this structure:
```
{
  _id: "1234",
  name: "John",
  addresses: {
    { street: "King St.", number: 1},
    { street: "Queen St.", number: 2}
  }
}
```

And it is possible to list/edit the addresses of a specific person.
In this case I would have a table with John's addresses like this:

Street | Number | Edit
------------ | ------------- | -------------
King St. | 1 | [Button]
Queen St. | 2 | [Button]

When clicking in the button you can edit that specific document.

---
Is it possible to do this with the current version of tabular? I have tried a couple of ways but none of them worked.

Or should I make a second collection, like PersonAddresses?

The part about editing I did with Autoform ( http://autoform.meteor.com/update-array-item and http://autoform.meteor.com/updatepush ), my only concern in this part is about sending the array index from tabular to autoform.

**Comment by aminjam** [comment]
+1 I am running into the same issue. My collection contains an array of objects, and I like to use `tabular` to display the table. I hope there is solution for it with the current version of `tabular`

**Comment by aldeed** [comment]
Not supported. I don't think you really need the benefits that tabular pkg provides if there is only one document providing the data. It's possible the pkg could provide a "simple mode", though, where it does the DataTables hookup for you but none of the advanced subscription stuff.

**Comment by lucasfurlani** [comment]
I did it using another collection for the subdocuments, it works like a charm.

The "simple mode" is a great idea @aldeed , it would allow tabular to fit in more use cases :)

**Comment by nickich** [comment]
I have the same issue - a table within a document. Probably will go with separate collection...
It would be cleaner if I have a chance to preserve the table as part of the current document though.

**Comment by kevinpeter** [comment]
+1

**Comment by dropfen** [comment]
+1 simple-mode for simple `data` 
It should just work like this: http://datatables.net/manual/data#Arrays

**Comment by aldeed** [comment]
Consolidating to #58

**Comment by neal-eiger** [comment]
Another vote for client-only collection support, has this been / will this be supported?
