### ISSUE TITLE
Collection Helper to prefix a "$" sign to a cell

### ISSUE THREAD

**Issue by ababra** [aldeed/meteor-tabular#103]
Here's my simple Mongo collection:

````meteor:PRIMARY> db.tests.insert({test_name: "Test", test_price: 60, test_duration: 12})````

Table definition:

    Tests = new Mongo.Collection("tests");
    TabularTables.Tests = new Tabular.Table({
      name: "Tests",
      collection: Tests,
      columns: [
        { data: 'test_name', title: 'Test Name' },
        { data: 'testPrice()', title: 'Price' },
        { data: 'test_duration', title: 'Duration', visible: false }
      ]
    });

Collection helper (using dburles:collection-helpers):

    Tests.helpers({
      testPrice: function() {
        return '$' + this.test_price;
      }
    });

The above does not work, I keep getting "$undefined". However, this works perfectly (returns "$Test"):

    Tests.helpers({
      testPrice: function() {
        return '$' + this.test_name;
      }
    });

Tried changing the field name in the Mongo collection, thinking "price" is somehow reserved, but no luck. Thought it could be an issue with how Mongo DB is storing the value (int. vs. string), however this also works perfectly (returns "$12"):

    Tests.helpers({
      testPrice: function() {
        return '$' + this.test_duration;
      }
    });

I am at a loss to explain why just the "test_price" field does not work inside of the collection helper, yet all other fields do.

**Comment by aldeed** [comment]
Tabular dynamically subscribes to only the necessary fields, and since you don't have `test_price` listed in any `data` props, it does not subscribe and therefore it is undefined on the client. You can use [extraFields](https://github.com/aldeed/meteor-tabular#publishing-extra-fields) to tell tabular to subscribe to `test_price`.

**Comment by ababra** [comment]
Thanks, that worked!
