### ISSUE TITLE
Adding edit/delete row buttons

### ISSUE THREAD

**Issue by ababra** [aldeed/meteor-tabular#104]
Does anyone have any code examples on how to implement edit/delete row functionality? Would be great if some working samples could be provided. There are examples that are for AJAX/DataTables, but nothing Meteor-centric.

**Comment by aldeed** [comment]
A delete example would be like [this example](https://github.com/aldeed/meteor-tabular#template-cells), except replace `addBookToCheckoutCart(this._id);` with `Books.remove(this._id)`. Similar idea for edit, but you'd probably do `Router.go` to an edit route, passing in `this._id`.

**Comment by ababra** [comment]
OK here's my code:

Javascript:

    col_tests = new Mongo.Collection("tests");

Had to add this, otherwise get "access denied" when deleting:

    col_tests.allow({
      remove: function (userId, post) {
        return true
      }
    })

Event handler:

    Template.datatables_actions.events({
      'click #datatables_actions_delete': function() {
        col_tests.remove(this._id);
        // Non-reactive way to get the table to reload
        location.reload();
      }
    });

Template HTML:

    <template name="bt_datatables_actions">
        <div id="datatables_actions_edit" class="ui icon basic button">
            <i class="edit icon"></i>
        </div>
    </template>

Row gets deleted just fine, however table won't refresh reactively (hence the need for the location.reload).

**Comment by aldeed** [comment]
It should reactively update. Can you link to a reproduction of the nonreactivity issue on MeteorPad?

**Comment by vicusbass** [comment]
I have the exact same thing in a tabular table, it's reactively updated after a delete or an update. I tried it with 2 browsers opened, etc. All good.
