### ISSUE TITLE
Move bootstrap theme to separate package and support all themes

### ISSUE THREAD

**Issue by boustanihani** [aldeed/meteor-tabular#105]
It would be nice if meteor-tabular also allows us to choose from the list of supported CSS frameworks, other than bootstrap: http://www.datatables.net/manual/styling/

**Comment by aldeed** [comment]
I agree, but I want to get it stable limited to bootstrap first.

**Comment by boustanihani** [comment]
I agree too :) :+1:

**Comment by aldeed** [comment]
Done in 2.0
