### ISSUE TITLE
Support adding a footer

### ISSUE THREAD

**Issue by joshperrin** [aldeed/meteor-tabular#110]
Hey there,

I feel like i'm missing something easy here. But how do you go about adding a footer with tabular? 

I've looked at many datatables examples. However they all show the footer added in the html, and then using different functions like the footerCallback, and columns().footer(), to update it; however as tabular generates the html automatically, I haven't been able to create a footer with tabular. I'm sure this is something easy i'm missing so any help, or a simple example would be much appreciated! 

thanks so much (and thanks for this great package)!

**Comment by aldeed** [comment]
Not really sure. Maybe will have to add the ability to provide a footer template name.

**Comment by joshperrin** [comment]
Maybe there's a better way to do this then. What i'm really looking to do is add a row which tallies the totals from the columns. So it doesn't necessarily need to be a footer.

Is there a way to add rows instead of columns, or is there a good way to achieve this that you can think of?

**Comment by willrbc** [comment]
The footer is a key feature for me too. I'm building a reporting system for a client and I'd like to have a totals row at the bottom,  I'll probably just show the totals outside of the table for now.

**Comment by mazing** [comment]
+1

**Comment by rolivav** [comment]
+1

**Comment by crapthings** [comment]
+1

**Comment by Kibukita** [comment]
+1

**Comment by ramzwatcher** [comment]
+1

**Comment by serkyen** [comment]
+1

**Comment by emilianomacias0** [comment]
+1

**Comment by aldeed** [comment]
Pretty sure this will work in 2.0
