### ISSUE TITLE
Tracker recompute error when sorting

### ISSUE THREAD

**Issue by rustanacexd** [aldeed/meteor-tabular#112]
I am having this error when trying to sort my custom field(clicking the sort button on the table). I don't have any problems when not sorting it.

"Exception from Tracker recompute function: Cannot read property 'server' of undefined
TypeError: Cannot read property 'server' of undefined"

I have this as a collection helper:
```
Domains.helpers({
    hostName: function () {
        var serverId = Domains.findOne(this._id).server;
        var server = Servers.findOne(serverId);

        if (server !== undefined) {
            return '<a href="/server/' + serverId + '">' +
                server.hostAccount + '</a>';
        } else
            return "None";

    }
});
```
and this part on the table
```
.....
columns: [
        {data: "name", title: "Domain Name"},
        {data: "type", title: "Type"},
        {data: "hostName()", title: "Server"}
.......
```

**Comment by aldeed** [comment]
Instead of `Domains.findOne(this._id).server`, can't you do `this.server`?

**Comment by rustanacexd** [comment]
nice. I have not thought of that. Thanks a lot again! problem solved :)

**Comment by rustanacexd** [comment]
uhmmm one problem though. I changed it to ``this.server`` but it always return "None" on my if-else statement. I checked via chrome console and the server property is clearly there.

**Comment by aldeed** [comment]
Is the `Servers` doc published to the client? If there are too many to publish them all, you may need a custom tabular publish function like in [this example](https://github.com/aldeed/meteor-tabular#example-1).

**Comment by rustanacexd** [comment]
Yes it is. I only have 10  to 20 servers on my app. I just tried to ```Servers.find().count()`` and the servers are clearly published. I'm confused why it is not showing.

**Comment by aldeed** [comment]
Oh, add `extraFields: ['server']` in your table definition. See https://github.com/aldeed/meteor-tabular#publishing-extra-fields

**Comment by rustanacexd** [comment]
ah yes it is working now! nice! thanks a lot! :)
