### ISSUE TITLE
How to filter columns from a helper?

### ISSUE THREAD

**Issue by miri-am** [aldeed/meteor-tabular#114]
How would it be possible to filter data from a helper? For example, how could the fullName from the example be searched? Is this possible or do I need to transform the data, so that the data actually exists in the collection?

```
People.helpers({
  fullName: function () {
    return this.firstName + ' ' + this.lastName;
  }
});
```

**Comment by brylie** [comment]
A related feature request is to be able to sort collection helper columns.

**Comment by KyleKing** [comment]
+1

I'm having the same issue. I have a collection which includes a unix timestamp in ms. With a collection helper, I reformat the timestamp into HH:MM format, but the table can no longer be sorted by that property.

Is there a better way to do somethign basic like this? Is there a way to retain sorting without changing the original timestamp format in the collection?

**Comment by brylie** [comment]
@KyleKing for what it's worth, we switched to the [aslagle:reactive-table](https://github.com/aslagle/reactive-table) package to have the ability to 
* pass table data in from template helpers
* as create custom filter widgets.

**Comment by aldeed** [comment]
This is essentially a duplicate of #162. Not yet supported. If the data is in the same collection, you just need to make sure there's a `data` property in addition to `render`, or include hidden columns that have the `data` prop you want to search on. But date searches and search strings that match the transformed text aren't supported and in some cases might not be possible.
