### ISSUE TITLE
Localization is needed for column title

### ISSUE THREAD

**Issue by koman1991** [aldeed/meteor-tabular#115]
``` js
columns: [{
      data: "category",
      title: "category",
      render: function(val, type, doc) {
        if (val) {
          for (var i = 0; i < categories.length; i++) {
            if (categories[i].id === val) {
              return (categories[i].en).concat(' ').concat(categories[i].tc);
            }
          }
        } else {
          return 'error';
        }
      }
    }, 
  ]
```

Currently the render function only change the data but not title
How can I translate the title in different language?

**Comment by miri-am** [comment]
you should be able use https://github.com/anticoders/meteor-i18n and then use ```title: i18n('category'); ```

**Comment by stephentcannon** [comment]
It would be nice if title were a function for cases where the locale is reactive, users change locale by clicking flag icon, and then column title would be redrawn nicely.

**Comment by VansonLeung** [comment]
Pull Request: #257

**Comment by thearabbit** [comment]
Now, could I use `titleFn`?
+1

**Comment by VansonLeung** [comment]
No, you cannot
My PR is not being noticed

**Comment by thearabbit** [comment]
So, could I use your fork repo instead?
(clone and use it as local package)

**Comment by VansonLeung** [comment]
https://github.com/VansonLeung/meteor-tabular

In my fork, in addition to "titleFn", it also supports dynamic columns:


TabularTables.Dbtablerecords = new Tabular.Table({
  name: 'Dbtablerecords', collection: Dbtablerecords, responsive: true, autoWidth: false, stateSave: true,
  limit: 50,
  extraFields: ['_id'],
  order: [[4, 'desc']],
  columns_ref: (userId) => {
    console.log("UserId: " + userId);
    if (Roles.userIsInRole(userId, 'manage-team', 'manchester-united.com')) {
    return [
      {data: '_id', class: '_id hidden'},
      {data: 'name', title: 'Name'},
      {data: 'schema_name', title: 'Schema Name'},
      {data: 'is_schema_only', title: 'Is Schema Only'},
      {data: 'make_priority', title: 'Make Priority'},
    ]
    }
    return [
      {data: 'name', title: 'Name'},
    ]
  },
});

**Comment by thearabbit** [comment]
Thanks again, I will this.
Could I install it via `atmospherejs`?

**Comment by VansonLeung** [comment]
yes,
meteor add vansonhk:tabular

**Comment by aldeed** [comment]
`titleFn` column option can be set to a reactive function in v2.0

**Comment by thearabbit** [comment]
Look great!!!

**Comment by thearabbit** [comment]
I tried but

![2016-10-31_16-41-57](https://cloud.githubusercontent.com/assets/4495160/19850090/25890f7c-9f89-11e6-96ac-e66d552705eb.png)
