### ISSUE TITLE
runs out of memory when adding lots of records

### ISSUE THREAD

**Issue by bilkusg** [aldeed/meteor-tabular#118]
Using the example code in the readme, I can get the package to work, and if I already have lots of data in my collection all is fine.

However, if I want to add 20,000 new records to the database with a single button click, the server-side
update crashes with 'range error -  out of memory' roughly half-way through the update.

If the tabular template has never been rendered, there is no problem. But if it was previously rendered
and is now temporarily removed from the DOM, the memory problem still occurs.

As far as I can tell, the problem is caused by the observer not coping with such a large number of new records at once. Is this a bug, and if not, what's the workaround?

The relevant code is:

    Meteor.methods({
         addBook: function (csvObject) {
         csvObject.createdAt = new Date();
         Books.insert(csvObject);
      },
    DoTestAdd: function(v1){
      if ( Meteor.isServer) {
        for(cr=0;cr<20000;cr++) {
        var i = cr + v1;
        var v = {title:"Book " + i, author:"Author " + i,summary:"A new book",copies: i%2};
        Meteor.call("addBook",v);
        console.log("addBook " + i);
        }
      }
    },
    });

**Comment by aldeed** [comment]
Latest release has better performance and you can use a new `throttleRefresh` option as a fallback if you expect massive changes in a short period of time.
