### ISSUE TITLE
extraFields not passed to custom publication

### ISSUE THREAD

**Issue by projik** [aldeed/meteor-tabular#122]
When you specify a custom publication and specify `extraFields`, the `extraFields` do not get passed to custom publication. E.g.

    TabularTables.Posts = new Tabular.Table( {
        name: 'PostsTable',
        collection: Posts,
        extraFields: [comments, author],
        pub: 'tabular_Posts',
        columns: [{
            data: "title",
            title: "Title"
        }, {
            data: "created",
            title: "Date"
        }]
    });

In the custom publication, only the column `data` fields get passed in the arguments:

    Meteor.publishComposite('tabular_Posts', function(tableName, ids, fields) {
        console.log(fields); // {title: 1, created: 1}
        ...
    }

The `tabular_genericPub` function extends the `fields` object with `table.extraFields` inside the publish function

    Meteor.publish("tabular_genericPub", function (tableName, ids, fields) { 
        ...
        if (table.extraFields) {
            _.extend(fields, table.extraFields);
        } 
        ...
    })

I'm not sure why the fields object doesn't get extended before the publish function. It would be great if the custom publish functions received the extended `fields` object or update the documentation on the custom publications to show an example.

BTW thank you for writing this package in JavaScript and not CoffeeScript :)

**Comment by faceyspacey** [comment]
the following fix in tableInit.js solves it:

````
template.tabular.fields = _.extend(fields, tabularTable.extraFields);
template.tabular.searchFields = _.extend(searchFields, tabularTable.extraFields);
````

I'd make a pull request but i already have a solid one that's been waiting for a while. he must be really busy. u may like the feature i added for what ur doing as well. it allows u to provide a function as the ```pub``` option so u can have finer grain control on the subscription/publish params:


https://github.com/aldeed/meteor-tabular/pull/123

**Comment by lynchem** [comment]
I just starting using this package and I'm having this exact same problem. I did this for now but it would be nice if the package was updated to include them.

    Meteor.publishComposite('eventsComposite', function(tableName, ids, fields) {

        fields = _.extend(fields, TabularTables.Events.extraFields);

**Comment by sylido** [comment]
+1 seems like a pretty obvious bug.

**Comment by flanamacca** [comment]
+1 Confirming that lynchem's solution fixes it as well.

**Comment by TomFreudenberg** [comment]
+1 Still wondering why no official feedback from Eric ( @aldeed ) 

Hopefully this makes it fast into package.

**Comment by aldeed** [comment]
Agree this makes sense. I'll accept a PR or do this on my next sprint.

**Comment by flanamacca** [comment]
I would argue there was no feedback for a week since @aldeed has a life and needs sleep :).  If i find any time over the next few days ill swing a PR for you.

**Comment by evolross** [comment]
+1

**Comment by sylido** [comment]
@evolross you have to substitute the `Events` in `TabularTables.Events.extraFields` with the name of the table for which you need the extra fields. If you have two or more tables using the same publishComposite publication, I think you'll need to add some extra logic to account for that - i.e. check the `tableName` argument or `TabularTables[tableName].extraFields` should also work

**Comment by Custos** [comment]
@aldeed did you ever get to this?  If not I can try taking a stab since this is impacting me right now :).

**Comment by Custos** [comment]
For clarification to anyone that lands here:

When calling TabularTables make sure that the format is TabularTables.<table name>.extraFields

For example:
  if (TabularTables.MyTable.extraFields) {
    _.extend(fields, TabularTables.MyTable.extraFields);
  }

**Comment by aldeed** [comment]
Done in 1.5.1
