### ISSUE TITLE
Remove tabular autoruns when user is not logged in

### ISSUE THREAD

**Issue by lucasfurlani** [aldeed/meteor-tabular#124]
Hello there!

I am trying to stop tabular from executing anything after the user clicks a "Logout" button. 
I have tried to do this in several ways but the template autorun always runs before anything I do.

What is the best way to achieve that? I have a problem with this because I am getting data based on the route that the user is in, and when the user is not logged in there is no data, so the Tabular.Table instances throw errors (because they automatically call their selector function whenever I change a route).

Thanks!

**Comment by aldeed** [comment]
This possibly could be solved by wrapping the table in an `#if` and the setting that reactive condition to `false` and doing `Tracker.flush()` BEFORE logging out.
