### ISSUE TITLE
can customize the data source?

### ISSUE THREAD

**Issue by fooying** [aldeed/meteor-tabular#128]
I hope to show the data that like the result of mongodb's group method, can not through find, meteor now also does not support group method, so I wrote a method to realize the classification, I think this how to customize the data source from my custom methods results?

**Comment by aldeed** [comment]
I don't think it will currently be possible, but some of the other datatables packages may support it. This package is specifically for large collections that need optimized subscriptions. I may add support for other data sources in the future.

**Comment by fooying** [comment]
ok
