### ISSUE TITLE
"processing" message doesn't appear

### ISSUE THREAD

**Issue by lionelromanelli** [aldeed/meteor-tabular#130]
Why I can't see "processing" message when the page is changing?

I'm using the basic configuration:

{{> tabular table=TabularTables.Col class="table table-striped table-condensed"}}

TabularTables = {};
Meteor.isClient && Template.registerHelper('TabularTables', TabularTables);

TabularTables.Col = new Tabular.Table({
 name: "Col",
 collection: Col,
 columns: [{
  data: "code",
  title: "Code"
 }, {
  tmpl: Meteor.isClient && Template.actions
 }]
});

**Comment by lionelromanelli** [comment]
I tryed putting the "processing: true" option.
The html code generated contains block "<div id="DataTables_Table_0_processing" class="dataTables_processing" style="display: none;">Processing...</div>", but it isn't showing when I load the table or I change the page.

**Comment by vicusbass** [comment]
I have the same problem, a spinner or the "Processing" message would be great while data is being loaded

**Comment by thebarty** [comment]
Plus one!

**Comment by cannin** [comment]
I also needed this feature, I used Template.subscriptionsReady as a workaround: 


    Template.tabularContainer.onCreated(function () {
      this.subscribe("collection");
    });

    {{#if Template.subscriptionsReady}}
      {{> tabular table=TabularTables.Collection class="table table-striped table-bordered table-condensed" id="main"}}
    {{else}}
      <i class="fa fa-refresh fa-spin"></i>
      <p>Loading...</p>
    {{/if}}

**Comment by aldeed** [comment]
Fixed in 1.5.0
