### ISSUE TITLE
Using DataTables Editor

### ISSUE THREAD

**Issue by dh1tw** [aldeed/meteor-tabular#131]
Hey, 

I'm struggling a bit with DataTables optional Editor. In order to use Editor, the [docs](http://editor.datatables.net/manual/getting-started) tell me to initialize the editor in a variable:

    var editor = new $.fn.dataTable.Editor( {} );

I presume it is a namespace problem, but I can't find a suitable place to initialise and the access the editor variable from within TabularTables constructor / object. 

The most natural thing would be to initialise as follows, right? 

````javascript
TabularTables = {};

Meteor.isClient && Template.registerHelper('TabularTables', TabularTables);


TabularTables.Projects = new Tabular.Table({
  name: "BookList",
  collection: Projects,
  dom: 'T<"clear">lfrtip',
  columns: [
    {data: "name", title: "Name"},
    {data: "description", title: "Description"},
  ]
});

if (Meteor.isClient){
    editor = new $.fn.dataTable.Editor( {} );
}

````

However, this throws me the following Error message in my browsers debug console:

    [Error] TypeError: undefined is not a constructor (evaluating 'new $.fn.dataTable.Editor( {} )')
	(anonymous function) (tabular.js, line 17)

Is anyone already using DataTables Editor successfully together with Meteor-Tabular? 

Any hint appreciated!

Thanks!

**Comment by pdavidow** [comment]
I got it hooked up, and am able to query the 'editor' object in the console :)  
Try putting your above code inside of
Meteor.startup(function () {
// insert here
}

**Comment by smohantyCME** [comment]
> I got it hooked up, and am able to query the 'editor' object in the console :) Try putting your above code inside of Meteor.startup(function () { // insert here }
> 
> And make sure you park the Editor code under client/compatibility.

Where exactly should we put the Editor code and then DataTables code?
