### ISSUE TITLE
Possible to sort on columns from templates?

### ISSUE THREAD

**Issue by soitech** [aldeed/meteor-tabular#135]
I have a table with a "Date" column. It is very important to be able to sort the table by this date, but the date is returned from a template, as it can change based on a dropdown in another column. Is there any way to make the column orderable based on the rendered date that is displayed?

I've read through tabular documentation and dataTables api several times but not found a solution.

**Comment by soitech** [comment]
After adding collection-helpers and getting nowhere, I achieved some measure of success using columns.data() and columns.render() from the DataTables api. data() seems to enable to sorting, but setting sort:... with data would only sort asc, not desc. setting sort:... under render() sorts correctly, but without something in data() sorting wasn't enabled. It still doesn't work perfectly, especially after a date is changed from elsewhere, but it's a start.

**Comment by aldeed** [comment]
You can only sort if there is also `data` for the column. There is just no way to sort otherwise because that info won't be on the server, where the sorting happens.

**Comment by soitech** [comment]
That makes perfect sense. 
Does it check the data each time it is asked to sort, or does it cache and reuse the initial data? I'm still struggling a bit with sorting on data that changes occasionally.
