### ISSUE TITLE
Remove Datatables JS & CSS from package

### ISSUE THREAD

**Issue by ababra** [aldeed/meteor-tabular#139]
I am using Semantic UI in my project and ended up having to turn this into a local package, because I needed to modify the included DataTables CSS & JS files. Are those the stock DataTables files, or were they modified specifically for this package? If they were removed from this package's distribution, it would make customization a lot easier and you wouldn't need to release an update every time a new DataTables version comes out.

I will post example code of styling this with Semantic UI somewhere, when my project is complete.

**Comment by dandv** [comment]
:+1:

**Comment by rcarter** [comment]
+1

**Comment by srault95** [comment]
+1

**Comment by Ethaan** [comment]
+1

**Comment by aldeed** [comment]
As far as I can tell, there is no minimal and reliable Meteor pkg that pulls in the DataTables library. I did not want to get stuck maintaining one, so I just included the files directly. I agree it would be better to rely on a separate pkg. Anyone want to publish and maintain a pkg that includes just the DT js and css files?

**Comment by aldeed** [comment]
Current release uses NPM package for DT library. The bootstrap files are still included, but those will be moved to a separate package when #105 is done
