### ISSUE TITLE
Possibly Improving Speed for Sort/Pages/Search?

### ISSUE THREAD

**Issue by voidale** [aldeed/meteor-tabular#14]
There is some kind of a "moment" loading if you change pages, sort or filter. After visiting all pages (So I get all subscription if I do console count) clicking quickly on next page you will see that delay or clicking on any sorting few times causes it to. And it happens with 20 or 500 records tables.

I have researched a little bit about datatables speed:

a) is it possible it's because of redraw of the rows? looking at:  [this stackoverflow question](http://stackoverflow.com/questions/16923784/performance-issues-with-rendering-in-datatables)  the draw() function defaults to true, setting it false can increase performance dramatically. 

b) cached(client-side collection) are not being re-used? If I change to a page I just was in, reuse cached collection for the table can be really nice for performance, combined with "x" limit for first subscription can make first 5 pages load instantly. If you set limit for 100 and each page has 20 records.

The speed is not an issue right now, I just decided to post this as an improvement possibly for the future.

**Comment by aldeed** [comment]
1.0 is released. Can you retest on 1.0 and let me know if your concerns remain? For point b, note the new `sub` option described in the readme.

Please see updated [README](https://github.com/aldeed/meteor-tabular/blob/master/README.md) for all features and options.

**Comment by aldeed** [comment]
Created #47 for the preloading idea. Otherwise I think there's nothing left to resolve here, so closing.
