### ISSUE TITLE
Deleting a row from table

### ISSUE THREAD

**Issue by suneillg** [aldeed/meteor-tabular#141]
I have insert and update working reactively. When I remove an item from a collections, it is not updating the table reactively. I currently have location.reload to reload the page to make it work. Any suggestions?
Thanks

**Comment by palra** [comment]
Same here

**Comment by AnnotatedJS** [comment]
Hi suneillg and palra,

Have a look at http://greatalbums.meteor.com/albums for a working demonstration of a Collection with  reactively CRUD using aldeed:tabular, aldeed:autoform

The source is on github, https://github.com/AnnotatedJS/GreatAlbums

You can signin with email "admin@demo.com" and password "password".

René
AnnotatedJS

**Comment by aldeed** [comment]
This should work properly in 1.3.0

**Comment by pmoulos** [comment]
Hi all,

@aldeed thanks for this awesome piece of work!

Unfortunately, row deletion is not working for me with version 1.4.2 and using `Meteor.call()` to delete documents on the server using methods.
Fixed with  
```
var table = $('#myTable').DataTable();
table.page.len(table.page.len()).draw();
```
in the `Meteor.call()` callback function.
