### ISSUE TITLE
Multi-sort - sort by multiple columns?

### ISSUE THREAD

**Issue by brylie** [aldeed/meteor-tabular#144]
I am filling in data for a [comparison table of data tables packages](http://reactive-table.meteor.com/). Does Meteor Tabular support 'multisort'? Presumably, 'multisort' means sorting by one column and sub-sorting by a second.

**Comment by almogdesign** [comment]
This does not work built in, this is something that I'm going to need

**Comment by brylie** [comment]
To perform multi-sort in DataTables, **shift-click** on multiple columns.

Here is a basic demo that has multi-sort by default:
http://meteorpad.com/pad/xNafF9N5XJNrFJEyG/TabularDemo

**Comment by bluefangs** [comment]
I needed something similar, and while googling, came across this issue. Although it's dated, you may do multi sort by defining it in the table schema:
```

new Tabular.Table({

    name: "someTable",
    collection: alerts,
    autoWidth: false,
    order: [
        [9, "desc"],
        [8, "desc"]
    ],
    pageLength: 25,
    columns: [.......]
});
```
