### ISSUE TITLE
Internationalization (i18n)?

### ISSUE THREAD

**Issue by brylie** [aldeed/meteor-tabular#147]
I am adding details about Meteor Tabular to a comparison of data tables packages. Is Meteor Tabular internationalized? What kind of i18n support is planned for the project?

**Comment by aldeed** [comment]
There is no specific support, but you can do it. You would internationalize the same way as with any DataTable, probably through render functions.

**Comment by drtomasso** [comment]
This worked for me (I'm using anti:i18n package):

```javascript
if(Meteor.isClient){
	$.extend( true, $.fn.dataTable.defaults, {
		language: {
				"lengthMenu": i18n("tableDef.lengthMenu"),
				"zeroRecords": i18n("tableDef.zeroRecords"),
				"info": i18n("tableDef.info"),
				"infoEmpty": i18n("tableDef.infoEmpty"),
				"infoFiltered": i18n("tableDef.infoFiltered")
			}
	} );
}
```

Add this before creating the Tabular table. It is as with datatables, just make sure it is wrapped in .isClient. Works with other settings as well.

Datatables language options: https://datatables.net/reference/option/language

**Comment by thearabbit** [comment]
Excuse me I use `TAPi18n`, and khmer (km).
```js
// client/config
import {TAPi18n} from 'meteor/tap:i18n';

$.extend(true, $.fn.dataTable.defaults, {
    language: {
        "lengthMenu": function () {
            return TAPi18n.__("tableDef.lengthMenu");
        }
    }
});

// lib/i18n
{
  "tableDef": {
    "lengthMenu": "ប្រវែង......"
  }
}
```
But don't work.
Please help me for example.

**Comment by derouck** [comment]
@thearabbit You need to make sure that your language is set to the appropriate language before you extend the table, otherwise you might be setting english again. That was the problem for me at least :)

**Comment by ddiazUNSJ** [comment]
I just needed to change the data labels, such as, Showing page x of y, Search,...,Previuos, Next ,etc. Datatables uses  Internationalisation plug-ins,  In order to make this type of internalization the language plug-ins is used. To continuation , the code of tabular configuration  is presented.

TabularTables.myTable=new Tabular.Table({
    name: "myTable",
    collection: Collection1,
    language: {
                "url": "https://cdn.datatables.net/plug-ins/1.10.19/i18n/Spanish.json"
            },
....
     responsive: true,

    columns: [
                    {data: "nombreAuthor", title: "Autor"},
                   ]
  });
