### ISSUE TITLE
Keyboard support, navigation, etc

### ISSUE THREAD

**Issue by brylie** [aldeed/meteor-tabular#148]
I am adding details about Meteor Tabular to a [comparison data tables packages](http://reactive-table.meteor.com/). What kind of keyboard support does Meteor Tabular have? E.g. navigation, shortcuts, etc.

**Comment by aldeed** [comment]
Any datatables plugin (such as [this](https://github.com/lzzluca/dataTableRowNavByKeyb) maybe) should work, but there is no out of the box support for it.
