### ISSUE TITLE
Dynamic generation of table

### ISSUE THREAD

**Issue by ihistand** [aldeed/meteor-tabular#149]
This is not an issue with the code, just a question:

I am attempting to generate a table that is dynamic, meaning that the column names can't be hardcoded because they are based on a collection that changes keys in the documents.  When I try to hard code it, it works perfectly, here's a simple example:

```javascript
TabularTables.SourceData = new Tabular.Table({
    name: "SourceData",
    collection: Collections.SourceData,
    columns:[ { data: '_id', title: '_id' },
        { data: 'ID', title: 'ID' },
        { data: 'FirstName', title: 'FirstName' },
        { data: 'LastName', title: 'LastName' },
        { data: 'fileId', title: 'fileId' } ]
});
```
But this dynamic version, which is trying to create the same exact table is coming up blank:

```javascript
// pull the first document in the collection
// and put each key into the columns array
var dataRecord = Collections.SourceData.findOne()
var dataColumns = [];

for (var key in dataRecord) {
    dataColumns.push({data: key,title: key});
}

var myTable = {
        name: "SourceData",
        collection: Collections.SourceData,
        columns:dataColumns
    };

TabularTables.SourceData = new Tabular.Table(myTable);
 ```
Any suggestions for what I'm doing wrong?
Thanks!
--Ivan

**Comment by aldeed** [comment]
I don't see an issue, but maybe you could put it into a simple example repo to replicate the issue.
