### ISSUE TITLE
Bug? No sorting with collection helpers

### ISSUE THREAD

**Issue by obiwarn** [aldeed/meteor-tabular#151]
I use yogiben:admin (which uses tabular).

When I add a collection helper row, this row is not sortable nor searchable. 
Not sure if this is a tabular bug or an admin bug.

**Comment by brylie** [comment]
This may be a feature request.

**Comment by brylie** [comment]
Possible duplicate of #114

**Comment by aldeed** [comment]
See https://github.com/aldeed/meteor-tabular/issues/162#issuecomment-121276002

**Comment by brylie** [comment]
This is an important feature for usability and 'robustness'. In effect, users will not differentiate between columns created by collection helpers, and may need to sort based on that data.

**Comment by obiwarn** [comment]
Yes. Right now we add a "(NO SORT)" label to these columns which is really sad.
