### ISSUE TITLE
click event firing on all rows

### ISSUE THREAD

**Issue by joshua1** [aldeed/meteor-tabular#152]
Hi @aldeed ,
I have a table with three rows of data with a template button on each row having an event to show a modal with other details. when a button for a given row is clicked, three modal windows pops up each representing a row. my event code and button template is below
```
'click .threadBtn': function(e){          
                Session.set('cusMsg', this);            
               // $('#closeModal').modal();
                $('#closeModal').modal().one('click', '[data-value]', function(e){
                    if($(this).data('value')){
                        selected = true;
                    }
                }).on('hidden.bs.modal', function(e){
                    console.log(selected);
                    if(selected === true)
                        setTimeout(function(){
                            me.submitThreadPost();
                        }, 300);
                });
            }
```
template button is 
```
<template name="customerMsgAction">
    <button type="button" class="btn btn-success threadBtn">View Details</button>
  </template>
```
Any help with this will be appreciated

**Comment by tjflaagan** [comment]
Since you're using threadBtn for the event and setting it to every button in the template it will call each one one on single click. 

Try something like this  (add in your modal logic)  but it should get you the data from the specific row. You can check out what data that gives you with some console logs.

    'click tbody > tr': function (event) {
      var dataTable = $(event.target).closest('table').DataTable();
      var rowData = dataTable.row(event.currentTarget).data();
    }

**Comment by joshua1** [comment]
Hi @aldeed I had to come back to this. how would this work if i have more than one column with buttons per row of data

**Comment by aldeed** [comment]
@joshua1 I'm not sure I follow what's going on. Are you able to post a simple reproduction?
