### ISSUE TITLE
Tabular doesn't work with Meteor Partitioner

### ISSUE THREAD

**Issue by jeroenpeeters** [aldeed/meteor-tabular#154]
It seems that Tabular doesn't work with Meteor Partitioner (https://github.com/mizzao/meteor-partitioner). As soon as a collection is partitioned, Tabular refuses to display any data. Even a custom publication won't help.

Is it possible to get Tabular to work with partitioned collections?

**Comment by greyarch** [comment]
Same problem here.

**Comment by aldeed** [comment]
I haven't used this, but it seems like it would work. Somebody will need to post a link to an app that reproduces the issue.

**Comment by dovrosenberg** [comment]
I am using Tabular to display partitioned data and don't have an issue.  I did make some tweaks to the partitioner package to support some other things I'm doing, but it's not immediately obvious to me that any of those would have 'fixed' Tabular.
