### ISSUE TITLE
Everything working as expected except for Search

### ISSUE THREAD

**Issue by lance-anderson** [aldeed/meteor-tabular#155]
Everything is working as expected: sorting by column, prev/next, changing the number of rows shown... it all works except for Search. When I type in the search box nothing happens. I've been starring at this for far too long now.

Any ideas as to what I might be missing?

I think I basically just copied the example code and tweaked "Books" to "Projects".

```javascript
TabularTables = {};

Meteor.isClient && Template.registerHelper('TabularTables', TabularTables);

TabularTables.Projects = new Tabular.Table({
  name: "ProjectList",
  collection: Project,
  columns: [
    {data: "name", title: "Project"},
    {data: "code", title: "Code"},
    {data: "note", title: "Note"},
  ]
});
```

and

```
  {{> tabular table=TabularTables.Projects class="table table-striped table-bordered table-condensed"}}
```

**Comment by riiiiizzzzzohmmmmm** [comment]
Not working for me either. I'll chime in with more deets when I get a chance to dig a little deeper into what might be going on.

**Comment by lance-anderson** [comment]
Curious to hear what you find @riiiiizzzzzohmmmmm. It's still not working for me. Turns out it's not just search that isn't working. I also couldn't get the ```extraFields``` or ```selector``` options to work either.

**Comment by riiiiizzzzzohmmmmm** [comment]
@lance-anderson you may just need to run `meteor update aldeed:tabular`. i noticed that when i originally added the package via `api.use` in one of my own packages, meteor added a slightly older version, but once I updated the package to the latest version, search started working.

haven't test `extraFields` or `selector` yet.

**Comment by lance-anderson** [comment]
THANK YOU @riiiiizzzzzohmmmmm!!! That was totally it and I wouldn’t have figured that out on my own.  In case others run across this thread, I ran the ```meteor update laded:tabular``` command which upgrade the package: ```aldeed:tabular*  upgraded from 0.1.0 to 1.2.0 ``` but I also had to manually update Meteor's ```versions``` file. It’s amazing anything was working with version 0.1.0! Now everything is working as expected.
