### ISSUE TITLE
Memory issues with large subscription

### ISSUE THREAD

**Issue by maxko87** [aldeed/meteor-tabular#156]
I have a table of about 10,000 items, each about 1kb in size. From what I understand, this package should only subscribe to each page of items as opposed to the whole collection. However, I'm encountering memory errors when loading this table. What I'd like to know is

- If tabular is doing a limit() on the number of items on a page, why does it take so much longer for larger subscriptions (when page size remains the same)? Could it be the default sort on the table that's causing it to scan all the docs?
- Is there a way to view the query that tabular uses so that I can see if it's using my indices?

**Comment by spobor** [comment]
Just in case it's the same - I was having a similar issue when I started playing around, realised I'd left autopublish on ;P

**Comment by maxko87** [comment]
Not my issue but thanks :)

**Comment by ryanswapp** [comment]
I am also trying to figure out how to fix this issue... Any updates?

**Comment by tinchoz49** [comment]
:+1: same here!

**Comment by nsparikh** [comment]
A couple of modifications I've made that speed up the initial load time on large datasets:
- Set the initial sort to none, so that there's no sort being run on the whole dataset upon initialization
- In server/tabular.js: wrap the countCursor.observeChanges().added() function with _.debounce to ensure that this method isn't fired unnecessarily for every doc upon initialization

I'll submit pull requests for these changes.

**Comment by tinchoz49** [comment]
that is great @nsparikh !

**Comment by maxko87** [comment]
Awesome @nsparikh, @aldeed can you accept the PR?

**Comment by rakish** [comment]
I would like to see this accepted as well. Thanks!

**Comment by bpartridge** [comment]
This may be related to the problem I was seeing here:

https://forums.meteor.com/t/observing-count-on-a-very-large-cursor/8681?u=bpartridge

**Comment by aldeed** [comment]
Default sort change is in 1.3.0 release. I want to test edge cases of debouncing before doing that. I think I thought of a case where it would cause problems, but now I can't remember what it was.

Also make sure you are not using a subs-manager or that you've optimized the caching settings of the subs-manager.

Also for performance in general of course make sure any props in the selectors are indexed.

There is definitely more that can be done to optimize performance. I appreciate any contributions in that regard, especially if you link to a nice example app showing the performance gain before and after.

**Comment by bySabi** [comment]
I create PR https://github.com/aldeed/meteor-tabular/pull/231 that improve render time a little on large dataset.

**Comment by aldeed** [comment]
Should be fixed in 1.5.0
