### ISSUE TITLE
Access to table instance.

### ISSUE THREAD

**Issue by belokonm** [aldeed/meteor-tabular#158]
Hi. Not an issue. Question. 
In client/tabular.js in line 231 you have next:
table = $tableElement.DataTable(options);

Is there any possibility to access table outside of tabular.js?

When I try to use: $('.bd').dataTable();  or $('.bd').DataTable(); it creates new table.

**Comment by aldeed** [comment]
`$('.bd').DataTable()` should work assuming you have `bd` class on the table element and you call it after the table has been rendered.
