### ISSUE TITLE
Custom filtering - range search

### ISSUE THREAD

**Issue by philipobrien** [aldeed/meteor-tabular#159]
Are there any examples of using tabular like DataTables are used in [this example](https://datatables.net/examples/plug-ins/range_filtering.html)? 

I have collections being rendered correctly in Tabular, but I am having difficulty figuring out how to search using a date range. Any help/direction would be most appreciated

**Comment by aldeed** [comment]
You cannot do it like in the example because the search needs to happen on the server, but there may be some way to support this in the future.

**Comment by Ajaxsoap** [comment]
+1 I would love to see this feature implement soon just like in [#162](https://github.com/aldeed/meteor-tabular/issues/162)
