### ISSUE TITLE
any way to retrieve the number of data elements the table has rendered?

### ISSUE THREAD

**Issue by rschiavi** [aldeed/meteor-tabular#160]
seeing a long delay with 1000s of data elements between when the initComplete fires and the table shows the data (ie, there's a 5 or so second delay when the table says "no results"). Would like to hide that until rendering is completed.

**Comment by aldeed** [comment]
Latest version has improved "processing" indicator like normal DataTables. That might be enough, or it could potentially emit some begin/end loading events in the future.

**Comment by aramk** [comment]
This can be done like so:

```
const tableTemplate = Blaze.getView(this.$('.dataTables_wrapper')[0]).templateInstance();
this.autorun(() => {
  const tabular = tableTemplate.tabular;
  const isLoading = tabular.isLoading.get();
  if (isLoading) return;
  console.log('done', tabular.data, tabular.recordsTotal);
});
```

I have this in the `onRendered()` hook. Basically, the tableTemplate is the template instance and `tabular` is a property which contains useful reactive variables and data. When isLoading is false, the table is done loading and `tabular.data` is the current page of data, while `tabular.recordsTotal` is the count of items in total across all pages.
