### ISSUE TITLE
Publish data is not displaying in aldeed:tabular

### ISSUE THREAD

**Issue by dhavalrajani92** [aldeed/meteor-tabular#165]
Hello Aldeed,

i am using aldeede:tabular package in my meteor app and i am giving "pub" option but its not taking publish data  instead of it is taking all data from collection i want data which is published below is my code please look into this

TabularTables.users = new Tabular.Table({
    name: "userList",
    collection: user,
    pub: "list_users",
    columns: [
    { data: "profile.name", title: "Name" },
    { data: "emails.0.address", title: "Email" },
    { data: "profile.role", title: "Role" },
    { data: "profile.mobile", title: "Mobile" },
    {
        tmpl: Meteor.isClient && Template.editUserButtons
    },
    {
        tmpl: Meteor.isClient && Template.deleteUserButtons
    }
  ],
    "dom": '<"table-heading"fl>t<"table-footer"ip>',
    order: []
   
});

**Comment by aldeed** [comment]
Please post your "list_users" publish function

**Comment by dhavalrajani92** [comment]
Below is my publish function 

Meteor.publish('list_users', function () {
    return user.find();
});

**Comment by aldeed** [comment]
`user.find()` would publish all data. You need to have it return the requested IDs like the example in the readme.

**Comment by jpmelnik** [comment]
Hello Aldeed,

TabularTable cannot render something like:

```
Meteor.publish('posts', () => {
	return Collections.Posts.find({
		visible : true
	});
});
```

Here the HTML

```
{{> tabular table=TabularTables.Posts id="PostsTable"  class="table table-striped table-bordered table-hover table-condensed"}}
```

And Tabular Instance:

```
TabularTables.Posts = new Tabular.Table({
	name: "Posts",
  collection: Collections.Posts,
  pub: "posts",
  extraFields: ['actions'],
  responsive: true,
  columns: [
  	{
  		data : "name",
  		title : "Nombre",
      tmpl: Meteor.isClient && Template.ObraSocialEditLink,
      tmplContext: function (rowData) {
        return {
          item: rowData,
          column: 'name'
        };
      }
  	},
  	{
  		data : "acronym",
  		title : "Acrónimo"
  	},
  	{
  		data : "slug",
  		title : "Slug"
  	},
  	{
  		data : "summary",
  		title : "Summary"
  	},
    {
      data : "Visible",
      title : "Estado",
      tmpl: Meteor.isClient && Template.ObraSocialVisibleCell,
      tmplContext: function (rowData) {
        return {
          item: rowData,
          column: 'Visible'
        };
      }
    },
    {
      data : null,
      title : "Acciones",
      tmpl: Meteor.isClient && Template.ObraSocialActions,
      tmplContext: function (rowData) {
        return {
          item: rowData,
          column: 'Acciones'
        };
      }
    }
  ]
});
```

**Comment by dhavalrajani92** [comment]
Hello jpmelnik,

I faced same problem with it. if you want to display some records in grid than it will not possible through pub thing in tabular code. Below code might help you to solve your problem.

Here is the javascript
```javascript
Template.Posts.helpers({
    selector:function (){
            return { visible : true};
    }
})
```

```
 {{> tabular selector=selector table=TabularTables.Posts id="PostsTable"  class="table table-striped table-bordered table-hover table-condensed"}}
```


This solution might help.

**Comment by jpmelnik** [comment]
Thank You.
I hope a fix for it next versions.

By the other hand I found that if  I put something like:

```
selector : function (){
    return { 
    	Visible : true
    };
  },
```
I get all Posts with Visible true. It's OK, but:

If I add one extra property like:
```
 return { 
       name : "something-here",
    	Visible : true
    };
```
If Visible is "true" nothing happend. But if Visible is "false" I can see the posts.

**Comment by dhavalrajani92** [comment]
Hello jpmelnik,

which thing you are passing in selector its one kind of mongo query. if you pass name:"something here", visbible: true then it will fire query with and condition that
```
 select * from Posts where name="something here" and visible: true;
```
got my point??

**Comment by jpmelnik** [comment]
Sure! It's exactly I want to do.

**Comment by dhavalrajani92** [comment]
yes than this thing will work.

**Comment by aldeed** [comment]
This looks like misunderstanding of how it works. See explanation here: https://github.com/aldeed/meteor-tabular/issues/240#issuecomment-170068339
