### ISSUE TITLE
Has anybody had success implementing Drag & Drop ordering or Numbered ordering?

### ISSUE THREAD

**Issue by ecuanaso** [aldeed/meteor-tabular#167]
Is there a way to implement either of these two things? 
<strong>Here's an example of  Drag and Drop ordering-></strong>
http://jquery-datatables-row-reordering.googlecode.com/svn/trunk/index.html

<strong>And this is an example of Numbered ordering</strong>
<img src="http://s25.postimg.org/7ujqks16n/Screen_Shot_2015_06_18_at_11_25_14_AM.png">

**Comment by aldeed** [comment]
I have not tried either.
