### ISSUE TITLE
Click not fired when something is entered in the search box ?

### ISSUE THREAD

**Issue by udiedrichsen** [aldeed/meteor-tabular#169]
I have a strange problem.

This event handler code works fine when I enter nothing in the search box:
'click tbody > tr': function (event, templ) {
    var dataTable = $(event.target).closest('table').DataTable();
    var rowData = dataTable.row(event.currentTarget).data();
 }

When I enter a text in the search field, the table is updated / filtered => fine, but the click event is not fired.

When I clear the search box, the event fires as usual.

**Comment by aldeed** [comment]
I tried and cannot reproduce this. Please create an example repo and post a link to it.

**Comment by udiedrichsen** [comment]
You are right ! I build a sample example using tabular and I don't have this issue 
So no bug in tabular :+1:
