### ISSUE TITLE
Publishing Too Restrictive, No Way to Override

### ISSUE THREAD

**Issue by jonlachlan** [aldeed/meteor-tabular#17]
I wanted to include my fields within the template, not as simple fields or using the renderer. For example, this way I could include a Product Info button right next to the product name, not within an adjacent cell. More importantly, I could make my template switch to an input form with a click event, making the table in-place editable (that would be hot!)

I can already do this (the input form at least, still working on the event code) if I add a duplicate column that brings the field I want into the collection, so it's clearly possible. However the publishing rules in the documentation only let you restrict further, it won't let you expand out to include more fields.

**Comment by jonlachlan** [comment]
I was able to use visible:false in order to create hidden columns that make the data available.

I believe the most intuitive way to do this would be to allow data:field to be present as well as tmpl:Temlate. Currently it doesn't seem to recognize the included data when this format is used.

**Comment by aldeed** [comment]
1.0 is released and should fix this. It is now possible to pass `data` along with `tmpl`, and there is also an `extraFields` option to use instead of hidden columns.

Please see updated [README](https://github.com/aldeed/meteor-tabular/blob/master/README.md) for all features and options.
