### ISSUE TITLE
Conflict with matb33:collection-hooks?

### ISSUE THREAD

**Issue by brylie** [aldeed/meteor-tabular#170]
I have a project using meteor tabular, which is part of [yogiben:meteor-admin](https://github.com/yogiben/meteor-admin/). When I add the [matb33:collection-hooks](https://github.com/matb33/meteor-collection-hooks/) package, I get the following error:

```
Error: Tabular.Table options must specify collection
     at new Tabular.Table (packages/aldeed:tabular/common.js:20:1)
     at packages/yogiben:admin/lib/both/startup.coffee:100:27
     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
     at adminCreateTables (packages/yogiben:admin/lib/both/startup.coffee:77:4)
     at __coffeescriptShare (packages/yogiben:admin/lib/both/startup.coffee:178:2)
     at /home/brylie/Code/Apinf/api-umbrella-dashboard/.meteor/local/build/programs/server/boot.js:229:5
```

I am not sure where the conflict resides, or the underlying issue, so I am filing this issue on each upstream package:
* [matb33:collection hooks #133](https://github.com/matb33/meteor-collection-hooks/issues/133)
* [yogiben:meteor-admin #226](https://github.com/yogiben/meteor-admin/issues/226)

**Comment by mordra** [comment]
We haven't worked out the underlying cause of this but everyone with this unfortunate issue seems to be able to get it working by tweaking the package loading order for a few sensitive packages:

https://github.com/yogiben/meteor-admin/issues/216#issuecomment-115451992

**Comment by brylie** [comment]
I have posted an issue describing the [load order of the 'comments' and 'collection-hooks' packages in yogiben:meteor-starter](https://github.com/yogiben/meteor-starter/issues/84) that may be the underlying cause of this issue.

**Comment by ffxsam** [comment]
What is "comments"? I don't have that package, whatever it is.
