### ISSUE TITLE
Show All option shows only one doc (instead of all docs)

### ISSUE THREAD

**Issue by AnnotatedJS** [aldeed/meteor-tabular#175]
I added the following option to tabular:

    lengthMenu: [ [10, 20, 40, 100, -1], [10, 20, 40, 100, "All"] ],

However, the All option shows only one doc (instead of all docs)

The lengthMenu option is described at http://datatables.net/reference/option/lengthMenu

**Comment by aldeed** [comment]
Duplicate of https://github.com/aldeed/meteor-tabular/issues/69
