### ISSUE TITLE
How to intergate with Sematic UI?

### ISSUE THREAD

**Issue by thearabbit** [aldeed/meteor-tabular#176]
I want to use this with `Sematic UI`.
Please help me.

**Comment by Ethaan** [comment]
+1

**Comment by aldeed** [comment]
The package includes the bootstrap theme right now, but I'd like to pull that out into a separate pkg and then there could also be a semantic theme add on.

**Comment by mbernath** [comment]
Hi there,

it is not a full pull request, but might be helpful to create a separate Semantic-UI styling package. Here's what I've done:

1. Clone meteor-tabular and remove the Bootstrap theme.
2. Install the semantic:ui package.
3. Write some styling LESS + JS for DataTables that builds upon the semantic:ui package.

This produces a nice Semantic-UI default view and could be used to create the Semantic-UI package.

datatables-styling.less

    @import (reference) "lib/semantic-ui/semantic.less";

    .dataTable {
      &:extend(.ui.table all);
      &:extend(.ui.sortable.table all);

      thead {
        th {
          &:extend(.ui.sortable.table thead th all);
        }
        th.sorting_asc {
          &:extend(.ui.sortable.table thead th.sorted all);
          &:extend(.ui.sortable.table thead th.ascending all);
        }
        th.sorting_desc {
          &:extend(.ui.sortable.table thead th.sorted all);
          &:extend(.ui.sortable.table thead th.descending all);
        }
        th.sorting_disabled {
          cursor: not-allowed;
        }
      }
    }

    .dataTables_length,
    .dataTables_filter {
      &:extend(.ui.form all);
      margin-bottom: 1em;
      label {
        &:extend(.ui.form .field > label all);
        &:extend(.ui.form .inline.fields > label all);
      }
    }

    .dataTables_length {
      float:left;
      label {
        .selection.ui.dropdown {
          min-width: auto;
          margin: 0 10px;
        }
      }
    }

    .dataTables_filter {
      float:right;
      label {
        margin-right: 0;
        input[type="search"] {
          &:extend(.ui.form .ui.input all);
          &:extend(.ui.form .inline.field > .ui.input all);
          width: auto;
          vertical-align: middle;
          margin-left: 10px;
        }
      }
    }

    .dataTables_info {
      float: left;
      border-top: 1px transparent;
      border-bottom: 1px transparent;
      &:extend(.ui.menu .item);
    }

    .dataTables_paginate {
      float: right;
      &:extend(.ui.menu all);
      &:extend(.ui.pagination.menu all);
      & .paginate_button {
        &:extend(.ui.menu .item all);
        &:extend(.ui.pagination.menu .item all);
      }
      & > span {
        display: inline-flex;
        position: relative;
        &:after {
          &:extend(.ui.menu .item:before);
        }
      }
    }

datatables-styling.js

    if (Meteor.isClient) {
      Template.tabular.onRendered(function () {
        $('.dataTables_length select')
        .addClass('ui dropdown')
        .dropdown({
          action: function (text, value) {
            $(this).siblings('.dataTable').DataTable().page.len(value).draw();
            $(this).parents('.ui.dropdown').dropdown('set selected', value);
          }
        });
      });
    }

**Comment by brianmingus** [comment]
+1

**Comment by brianmingus** [comment]
@mbernath please submit a pull request!

**Comment by mbernath** [comment]
@brianmingus I've had a look at the bootstrap implementation. To make the implementation clean, I'd rather not patch the dataTables_* classes as in the snippet above, but add native semantic ui classes to the table. That would be a ``client/lib/dataTables.semantic.js`` and maybe some additional styling in a separate CSS.
However the different themes/stylings should be split out into another package as @aldeed suggested.
I don't have time to do this this week, but maybe next week...

**Comment by sugeknowles** [comment]
@mbernath  I'm new to Meteor (day 3) and tried to get your mods above to work with tabular as my app is styled with semantic-ui but had no luck.  Any chance you can provide more detailed instructions on how to make this work?  No worries either way, I'll keep plugging away at it.

**Comment by izaakdo** [comment]
+1 @mbernath

**Comment by brianmingus** [comment]
@mbernath can you explain the approach in more detail? I don't know how DataTables works. Is the idea to work with the table layout that DataTables gives and to sprinkle in classes as need to get semantic ui to style it correctly? I had assumed a deeper integration where we specified the markup would be necessary.

**Comment by mbernath** [comment]
@brianmingus DataTables creates a table with some standard classes ``dataTables_*``. It is possible to modify this using custom DataTables renderers. This is what ``client/lib/dataTables.bootstrap.js``in meteor-tabular does. In addition there are some styles defined ``client/lib/dataTables.bootstrap.css``.

The solution I posted at the beginning of this thread is a hack. I imported the Semantic UI styles via ``@import`` and extended the existing dataTables classes with Semantic UI styles. This works, but it bloats the CSS. In addition the @import statement is not really good, because it always requires semantic ui to be installed at exactly this location. A bit looser coupling between meteor-tabular and Semantic UI would be great.

A better way would be:

1. Add Semantic UI classes to the generated table via a custom renderer. That would basically be a Semantic UI specific implementation of ``client/lib/dataTables.bootstrap.js``.
2. Finetune the appearance with some additional styles.
3. Pull out both Bootstrap and Semantic UI stylings into separate packages.

**Comment by AlexGreg** [comment]
+1

**Comment by steve-ross** [comment]
You can at least get the table styled correctly by doing: 
```class="ui sortable striped table"```

**Comment by steve-ross** [comment]
here is an example taken from the datatables site: https://datatables.net/examples/styling/semanticui.html

**Comment by aldeed** [comment]
In v2 there are no themes included and you can pull in NPM theme packages.
