### ISSUE TITLE
Doesn't render data from one collection but does from other

### ISSUE THREAD

**Issue by willrbc** [aldeed/meteor-tabular#177]
I am building a simple reporting tool to see data about Quotes and Jobs in both tabular and chart form.  I am using this package along with the maazalik:highcharts package.

I have two views, one to see jobs and filter by user and one to see customers and their totals.

The jobs one has all worked perfectly as expected but when I try to create a table reading from the 'Customers' collection it just says "No data available in table"  this is despite there being a chart drawn on the same view with data, that uses the same selector on the same collection.

I have done a lot of tweaking and reduced the table down to just one column and it works fine with the 'Quotes' collection. As soon as I switch to the 'Customers' collection, it's data disappears. 

What's the best way I can debug to see what data is actually being received?
````javascript

// the following displays no data:

TabularTables = {};

Meteor.isClient && Template.registerHelper('TabularTables', TabularTables);

TabularTables.Customer = new Tabular.Table({
    name: "Report",
    collection: Customers,
    columns: [{
        data: "company",
        title: "Customer"
    }]
});

````

**Comment by niklasp** [comment]
Check if your data is really published in with the Meteor Method in Browser Console like
`Customers.find().fetch()`

**Comment by aldeed** [comment]
I'm not sure what this would be without seeing a full reproduction.

**Comment by aldeed** [comment]
Closing pending full reproduction
