### ISSUE TITLE
Add a conditional class to values that are negative numbers?

### ISSUE THREAD

**Issue by fshequin** [aldeed/meteor-tabular#184]
Greetings......was wondering if it's possible to style negative numbers in a Tabular Table differently than positive numbers. I've tried using basic jquery, I'm calling that on the template rendered event for lack of knowing what table events are available......is there a way that will not forget the classes on a column sort?

any help is much appreciated....

**Comment by aldeed** [comment]
Use the `createdCell` function. See http://meteorpad.com/pad/po4u2FeJ59LuzSNKX/Leaderboard

**Comment by fshequin** [comment]
Thanks....worked like a charm.....! you rock!
