### ISSUE TITLE
Search fails if selector has top level `$or` operator

### ISSUE THREAD

**Issue by jfols** [aldeed/meteor-tabular#186]
[At the end of `getPubSelector`](https://github.com/aldeed/meteor-tabular/blob/master/client/pubSelector.js#L31), I think it should be an explicit `$and` of `selector` and `searches`.
Otherwise, the `$or` in the `selector` is extended with `searches`, resulting a search on the entire collection with everything or'ed.

```js
return { $and: [ selector, searches ] };
```
I can submit a PR later if you don't beat me to it :smile:

**Comment by aldeed** [comment]
Fixed in 1.3.0
