### ISSUE TITLE
Send data to publication 

### ISSUE THREAD

**Issue by sasikanth513** [aldeed/meteor-tabular#19]
Along with the three fields I want to send one more field to publication how to do that?

```
TabularTables.registrations = new Tabular.Table({
  name: "Registrations",
  collection: Participants,
  pub: "tabular_Registrations",//want to send one more value 
  columns: [
    {data: "_id", title: "Title"},
    {data: "edition", title: "Edition"},
    {data: "email", title: "Email"},
]
});
```
My requirement is

I have 1000 docs in one collection each has ```edition`` field and 
I want to display only one edition records in table with autosubscribe(which this package provides)

I want to send that ```edition```  id to publish function

my publish function

```
Meteor.publish("editionDocs",function(tableName, ids, and fields){
  return Participants.find({"edition":editionId}),{........});
});

**Comment by aldeed** [comment]
You do not need to handle the selector in your publish function. It is handled in a different built-in publication. Just pass `{edition:editionId}` as the value of `selector` attribute. See the "Example" section in the readme.

Also 1.0 is released. Please see updated [README](https://github.com/aldeed/meteor-tabular/blob/master/README.md) for all features and options.
