### ISSUE TITLE
Hide columns according to user

### ISSUE THREAD

**Issue by shactdeveloper** [aldeed/meteor-tabular#196]
Hi, is there a way to hide columns according to user role?
Like this:
if the Admin is seeing the table, then there is a column called: "Secret"
if any other user is seeing the table, then the field Secret is not published and there is no column called "Secret"

Thanks

**Comment by aldeed** [comment]
For the publish security piece of this, you would use `allowFields` as described here: https://github.com/aldeed/meteor-tabular#security

For hiding the column dynamically, possibly something like this would work: https://datatables.net/examples/api/show_hide.html

**Comment by luixal** [comment]
Kind of an old issue... but I'm having troubles with this.

I've tried something like:

```javascript
allowFields: function(userId, fields) {
    fields.username = 0;
    fields.dateupdated = 0;
    return fields;
}
```

And I got this error:

```
Exception from sub tabular_genericPub id hbefTkyAPiWE9ezeq MinimongoError: You cannot currently mix including and excluding fields.
```

Also, when doing simple:


```javascript
allowFields: function(userId, fields) {
    return false;
}
```

It doesn't make anything.

Any ideas on how to hide specific columns? Maybe it should be enough if ```false``` is returned by the ```render``` function.

Thanks!

**Comment by luixal** [comment]
Or just the opposite option to ```extraFields```...
```javascript
extraFields: ['firstName', 'lastName']
```
something like:
```javascript
forbiddenFields: ['firstName', 'lastName']
```

**Comment by odesey** [comment]
I know this is old and closed but hopefully this solution can help someone else in the future.

The key is that the ```fields``` object values must be `ALL (1)'s` or `ALL (0)'s` (this is a Mongo limitation). So if you are working with the Meteor.users Collection and want to ONLY publish certain fields you can do this:

```javascript
  allowFields: function ( userId, fields ) {
    delete fields["profile"]
    fields["profile.firstName"] = 1;
    fields["profile.lastName"] = 1;
    fields["profile.phone"] = 1;

    console.log(fields)
    return fields;
  }
```

Then if you do a `Meteor.users.find().fetch()` in the Chrome console, all your users will only have the specified field published.
