### ISSUE TITLE
Meteor 1.2 support

### ISSUE THREAD

**Issue by AdamBrodzinski** [aldeed/meteor-tabular#197]
After upgrading to 1.2 RC i'm getting the following error for images:

```
=> Errors while initializing project:

While building package tabular:
error: No plugin known to handle file 'images/sort_asc.png'. If you want this
file to be a static asset, pass the {isAsset: true} option to api.addFiles; eg,
api.addFiles('images/sort_asc.png', 'client', {isAsset: true}).
error: No plugin known to handle file 'images/sort_asc_disabled.png'. If you
want this file to be a static asset, pass the {isAsset: true} option to
api.addFiles; eg, api.addFiles('images/sort_asc_disabled.png', 'client',
{isAsset: true}).
error: No plugin known to handle file 'images/sort_both.png'. If you want this
file to be a static asset, pass the {isAsset: true} option to api.addFiles; eg,
api.addFiles('images/sort_both.png', 'client', {isAsset: true}).
error: No plugin known to handle file 'images/sort_desc.png'. If you want this
file to be a static asset, pass the {isAsset: true} option to api.addFiles; eg,
api.addFiles('images/sort_desc.png', 'client', {isAsset: true}).
error: No plugin known to handle file 'images/sort_desc_disabled.png'. If you
want this file to be a static asset, pass the {isAsset: true} option to
api.addFiles; eg, api.addFiles('images/sort_desc_disabled.png', 'client',
{isAsset: true}).
```

**Comment by AdamBrodzinski** [comment]
I can confirm that changing it to `  ], 'client', {isAsset: true});` works. I don't have enough time this week to PR though :frowning:

**Comment by aldeed** [comment]
Yeah, I saw that in the 1.2 release notes. Hopefully old Meteor doesn't choke on `isAsset` being there. I will merge a PR or fix on my next tabular sprint.

**Comment by AdamBrodzinski** [comment]
Cool thanks @aldeed! 

I just tried it on  1.1.0.2 and it doesn't throw when building but when going to the table page has an undefined error. Removing isAsset fixes it.... I guess changing the `versionsFrom` to 1.2 will make the packager choose a lower version for pre 1.2 apps?

**Comment by aldeed** [comment]
Probably whenever I update I will have to bump major version of this pkg and it won't be usable on < 1.2 anymore. Unless I can detect what the Meteor version is and keep both types of `api.use` in there depending.

**Comment by brylie** [comment]
We have upgraded our project to Meteor 1.2 without any issue.

**Comment by aldeed** [comment]
Yeah this was fixed awhile back
