### ISSUE TITLE
Uncaught TypeError: $(...).closest(...).DataTable is not a function

### ISSUE THREAD

**Issue by Christilut** [aldeed/meteor-tabular#198]
I'm using this snippet from the readme to get a click event going on the rows.
```js
Template.myTemplate.events({
  'click tbody > tr': function (event) {
    var dataTable = $(event.target).closest('table').DataTable();
    var rowData = dataTable.row(event.currentTarget).data();
  }
});
```

The event works but it gives me the following error:
```
Uncaught TypeError: $(...).closest(...).DataTable is not a function
```

Otherwise it all works fine.

**Comment by aldeed** [comment]
Hmm, that would indicate the DT library isn't loading. Does it work to do `$('table').DataTable()` in the browser console?

**Comment by Christilut** [comment]
No it doesnt, I'm getting the same error.
The plugin itself seems to work fine though, my tables are created as datatables.

**Comment by aldeed** [comment]
Strange. If you are able to create a simple app reproducing the issue, that might help. And check the versions file to verify you are using the latest release of tabular.

**Comment by Christilut** [comment]
I tried to recreate it but it just works as expected then. I've tried removing any code and packages that seem in any way related to this problem but no luck there either.

This is the package list I'm using, maybe thats of any help:
```
accounts-password          1.1.1  Password support for accounts
accounts-ui                1.1.5  Simple templates to add login widgets to an app
aldeed:autoform            5.5.0  Easily create forms with automatic insert and update, and automatic reactive v...
aldeed:collection2         2.3.1* Automatic validation of insert and update operations on the client and server.
aldeed:tabular             1.3.0  Datatables for large or small datasets in Meteor
autopublish                1.0.3  Publish the entire database to all clients
coffeescript               1.0.6  Javascript dialect with fewer braces and semicolons
insecure                   1.0.3  Allow all database writes by default
iron:router                1.0.9  Routing specifically designed for Meteor
meteor-platform            1.2.2  Include a standard set of Meteor packages in your app
peppelg:bootstrap-3-modal  1.0.3  Simple usage of bootstrap 3 modals.
tomi:upload-jquery         2.1.8  Client template for uploads using "jquery-file-upload" from blueimp
tomi:upload-server         1.3.0* Upload server for Meteor. Allows to save and serve files from arbitrary directory
twbs:bootstrap             3.3.5  The most popular front-end framework for developing responsive, mobile first p...
useraccounts:bootstrap     1.12.3  Accounts Templates styled for Twitter Bootstrap.
useraccounts:core          1.12.3  Meteor sign up and sign in templates core package.
useraccounts:iron-routing  1.12.3  UserAccounts package providing routes configuration capability via iron:router.
```

Any other ideas?
I could decimate my current project in a new branch and upload that somewhere, assuming the bug presists then.

**Comment by aldeed** [comment]
I see that tabular does not have a dependency on the jquery pkg and it maybe should. Make sure `meteor-platform` is at the top of the list in the .meteor/packages file. Or use a local copy of tabular pkg and add the `jquery` pkg dependency to see if that fixes it.

**Comment by Christilut** [comment]
Yep, that fixed it. Just had to add the jquery package (and removed the jquery.js I was using for it)

Thanks!

**Comment by lucasfurlani** [comment]
Had the same problem. I tried moving/removing all packages and nothing worked. Turns out it was because of a jquery.js inserted in the project like @Christilut , I was using two versions of jQuery (the manually inserted one was the 1.11.1). Removing it fixed the problem. :)

Thanks @aldeed  and @Christilut !
