### ISSUE TITLE
Ignores Allow function

### ISSUE THREAD

**Issue by davidsyoung** [aldeed/meteor-tabular#20]
Hey, this could be a really stupid issue - but I'm not really sure why it's not being called.

I'm trying to add a custom allow function and no matter what I put in allow it still doesn't get called. So what am I doing wrong? 

Many thanks for your time, fantastic package as well. So thank you.

<pre>
TabularTables.NutritionDatabase = new Tabular.Table({
  name: "NutritionDatabase",
  collection: Nutrition,
  columns: [
    {data: "name", title: "Name"},
    {data: "group", title: "Food group"},
    {data: "manufacturer", title: "Brand"},
    {tmpl: (Meteor.isClient && Template.nutrition_database_options), title: "Options", width: "50px"}
  ],
  allow: function(userId, fields) {
    return false;
  },
  order: [[0, "asc"]],
});
</pre>

That is my table definition code and every time the table renders with items as normal. I've also tried to put in console.log()'s etc and they never print.

**Comment by aldeed** [comment]
1.0 is released and should fix this. Please see updated [README](https://github.com/aldeed/meteor-tabular/blob/master/README.md) for all features and options.
