### ISSUE TITLE
How to create Child rows that show extra / detailed information 

### ISSUE THREAD

**Issue by ecuanaso** [aldeed/meteor-tabular#202]
So the DataTables API has a method for parent/child. My goal is to try to turn this into the meteor way of doing this as much as possible.
Here's the link to the webpage -> 
https://datatables.net/examples/api/row_details.html

So far the only thing I was able to just add a circle with the green + plus sign. Here's a screen shot->
http://postimg.org/image/l48bfikjf/

Since I'm using meteor things might be a little different, so I'm getting errors on the click event, basically i'm getting table undefined eventhough I defined it.
Here's a gist of the meteor code that i'm trying to turn into datatables parent/child method->
https://gist.github.com/ecuanaso/26596c32a95562701d8e

I spoke to one of the guys on the DataTables forums and he said->

"new Tabular.Table({}) is not returning a DataTables API instance. You would need to take a look into that library or ask its author to see what it is actually returning and how you can get an API instance."

Maybe one of the seasoned developers can help me detect what is returning the API instance of DataTables?

**Comment by aldeed** [comment]
Short answer: `$(theTableElement).DataTable()`

Here are a few suggestions:

1. Use `{ tmpl: Meteor.isClient && Template.detailsControl }` instead of what you currently have for the first column. Create the `detailsControl` template as single div.details-control element, or whatever you need for the toggle button to show up.
2. Define a `click .details-control` event with `Template.detailsControl.events`. Doing it this way ensures it's scoped properly. Your current onRendered event handling could be attached multiple times and end up firing on unexpected tables.
3. Then try something like this in the new event handler function:

```js
function (event, template) {
  var tr = $(event.currentTarget).closest('tr');
  var table = tr.closest('table').DataTable();
  var row = table.row(tr);
 
  if ( row.child.isShown() ) {
    // This row is already open - close it
    row.child.hide();
    tr.removeClass('shown');
  } else {
    // Open this row
    row.child( format(row.data()) ).show();
    tr.addClass('shown');
  }
}
```

Keep in mind that any data in the child table will not be reactive while it is shown. There might be some way to make it reactive, but I'd need to take a closer look at the situation.

**Comment by ecuanaso** [comment]
Thanks for your reply Aldeed. I have another task, that I need your input in since you're more experienced with DataTables than I am. 
1) So apparently function format ( d ) is the original data source for the row, right. But the way I have my schema is having a field that has a parentId. 

So what I want to show inside the child rows is the rows that only have parentId exists. But of course we have to filter those child rows by parent/child. Meaning I create a parent row lets say 'Products', then I create a child row and on the parentId field I choose that I want this row to be a child row to the parent-> looks something like this-> http://postimg.org/image/7zji4ndkr/

So how can I configure the format function to show rows that only have parentId that exists.

This gist that shows the format function and the click event for showing and hiding child rows.
https://gist.github.com/ecuanaso/98f249f2929cbe67c3c7

And here's the gist for my defined schema and collection/columns->
https://gist.github.com/ecuanaso/5c5bb50abe06420b53c8

**Comment by ecuanaso** [comment]
Thanks for your reply Aldeed. I have another task, that I need your input
in since you're more experienced with DataTables than I am.
1) So apparently function format ( d ) is the original data source for the
row, right. But the way I have my schema is having a field that has a
parentId.

So what I want to show inside the child rows is the rows that only have
parentId exists. But of course we have to filter those child rows by
parent/child. Meaning I create a parent row lets say 'Products', then I
create a child row and on the parentId field I choose that I want this row
to be a child row to the parent-> looks something like this->
http://postimg.org/image/qgdwvgtiz/

So how can I configure the format function to show rows that only have
parentId that exists.

This gist that shows the format function and the click event for showing
and hiding child rows.
https://gist.github.com/ecuanaso/98f249f2929cbe67c3c7

And here's the gist for my defined schema and collection/columns->
https://gist.github.com/ecuanaso/5c5bb50abe06420b53c8

**Comment by aldeed** [comment]
@ecuanaso, I think in your format function you just need to do another query and put rows in the table HTML based on that.

```js
function format ( d ) {
var html = '<table cellpadding="5" cellspacing="0" border="0" style="padding-left:50px;">';
orion.pages.collection.find({parentId: d._id}).forEach(function (page) {
  html += '<tr><td>' + page._id '</td></tr>';
});
html += '</table>';
return html;
}
```

**Comment by leocrawf** [comment]
This works perfectly. Thank you.

**Comment by jdnichollsc** [comment]
Hi guys, exist any example (Gist) ?
Thanks in advance, Nicholls

**Comment by jdnichollsc** [comment]
Guys, what do you think about it?

```
Template.myView.events({
  'click .details-control': function( event, template ) {

      var tr = $(event.currentTarget).closest('tr');
      var table = tr.closest('table').DataTable();
      var row = table.row(tr);

      if ( row.child.isShown() ) {
        // This row is already open - close it
        row.child.hide();
        tr.removeClass('shown');
      } else {
        // Open this row
        row.child('<table></table>').show();
        var data = row.data();
        Blaze.renderWithData(Template.childTable, data, $(row.child()[0]).find('td')[0]);
        tr.addClass('shown');
      }
  }
});
```

Regards, Nicholls
