### ISSUE TITLE
Problem Tabular with using in "Alertify Modal"?

### ISSUE THREAD

**Issue by thearabbit** [aldeed/meteor-tabular#203]
I use `Tabular` with `Alertify Modal` like this
```js
// Html
<template name="staffList">
   {{> tabular...........................}}
</template>

// JS
...events({
   'click .openAtertify': function(){
       alertify.custom('Title Name',  renderTemplate(staffList))
   }
})
```
- The first time to open, it is OK for all.
- But for the second time to open, we can't use `search, next/previous` so on.

**Comment by aldeed** [comment]
I will be more likely to fix this quickly if you can link to a simple reproduction app.

**Comment by thearabbit** [comment]
Now it is OK, when I config `template destroyed` in `alertify`.
Thanks.
