### ISSUE TITLE
Sorting of columns incorrect when using `tmpl`

### ISSUE THREAD

**Issue by yee379** [aldeed/meteor-tabular#208]
I have a column which i am rendering through `tmpl`. However, when i display the table and click on the column title to sort, the sorting is incorrect (ie not alphanumeric).

**Comment by harrymeice** [comment]
May I ask to see your code?

**Comment by aldeed** [comment]
Sorting will be correct as long as you also include the `data` property to sort on. If there is no corresponding data property, then sorting is impossible.
