### ISSUE TITLE
How to create custom filters the *best-practise* way?

### ISSUE THREAD

**Issue by thebarty** [aldeed/meteor-tabular#214]
Hi guys,

I started in topic in the meteor-forum - it would be cool if you guys could have a look at it.

Basically: **What is the easiest way to add custom filters** with this module **without having to do all the manual work**?

**This is the topic with more information:**
https://forums.meteor.com/t/best-practise-for-custom-filter-for-aldeed-tabular/10602/1

**Comment by 57even** [comment]
+1

**Comment by AdamBrodzinski** [comment]
@thebarty that's similar to what i'm doing too. It kind of sucks but at this point it's faster than re-writing a table in react with all these features.

**Comment by Ajaxsoap** [comment]
Hi @thebarty ,

Take a look at this [issue](https://github.com/aldeed/meteor-tabular/issues/162), KyleKing created a function for custom searching and sorting, I haven't tried it yet but it seems working.

**Comment by aldeed** [comment]
Unfortunately I haven't had to do anything complex yet so I don't have any best practice guidelines. I've used the same "selector builder" approach. The referenced packages are a good start. IMO, a good solution package would probably be generic, not tied to tabular, and then just return a selector reactively.
