### ISSUE TITLE
Custom filters

### ISSUE THREAD

**Issue by mazing** [aldeed/meteor-tabular#219]
In meteor-reactivetable, you can easily make custom filters (see https://github.com/aslagle/reactive-table/#custom-filters). Is this really not possible in this package? I like this package but I am really in need of custom filters, so I am afraid I have to choose reactive-table. Have I overlooked something?

**Comment by aldeed** [comment]
There is nothing baked in like this. See https://github.com/aldeed/meteor-tabular/issues/214

It makes sense to me that someone could create a separate package that only deals with filters and combines them into a reactive mongo selector. That can then be passed to the tabular table. Maybe it is possible for @aslagle to pull out the reactive-table filters implementation into its own package for that.
