### ISSUE TITLE
Customize the html

### ISSUE THREAD

**Issue by mazing** [aldeed/meteor-tabular#220]
I have found the styling section in http://datatables.net/examples/styling/index.html but is it not possible to change the elements placements? I want to place some elements right next to the search input, put the search input in a `panel-heading`, put the pagination in `panel-footer`, etc.

How is such customization possible?

**Comment by aldeed** [comment]
I'm guessing you can do what you want with a combination of [DOM positioning syntax](http://datatables.net/examples/basic_init/dom.html) and changing styles.
