### ISSUE TITLE
Search in all rows even when paginated

### ISSUE THREAD

**Issue by mazing** [aldeed/meteor-tabular#224]
I have enabled pagination in my table.

I want to search for a value in all my rows (also those not displayed at the current page).

I have tried

    dataTable.column( 0, { order: 'current' } ).data().indexOf( "value i'm searching for" );

but it will only search in the currently displayed rows.

I guess I should use

    dataTable.column( 0, { order: 'current' } ).search( "value i'm searching for" );

or something alike.

**Comment by aldeed** [comment]
Correct. You should use column searching because that then does the searching on the server.
