### ISSUE TITLE
Aldeed tabular sort the formatted number

### ISSUE THREAD

**Issue by marczzio** [aldeed/meteor-tabular#225]
Hi Guys.

I use `aledeed:tabular` as the datatables. it is very great and very fast render to show the data.
But I have a problem with sorting the formatted number.

1. I use `numeral:numeral` package to formatting the number.
2. I save the formated data in mongoDB
3. Then I use `aldeed:tabular` to show this data as the picture below.

![sort issue](https://cloud.githubusercontent.com/assets/15154331/10536644/b590d18a-7416-11e5-8075-757a966d3c12.png)

In the picture above, the "Nilai" column is sorted descending but the value was not right.

Is there anyone has the idea about this issues of mine??
Really appreciate the help

Thanks :)

**Comment by aldeed** [comment]
If you are saving the formatted number, then you are probably saving a string to the database. The sorting you see is correct for string sorting. If you want it to be sorted in numerical order, then you should also save the `Number` in the database, and your `data` for the column should be the property that stores the `Number`. You can use a `tmpl` that shows the formatted property, or just use numeral to format the displayed value on the fly.
