### ISSUE TITLE
Setting column title automatically from collection2

### ISSUE THREAD

**Issue by mazing** [aldeed/meteor-tabular#228]
In my app, I define the columns with

    columns: [
      { data: "_id", title: "Id", visible: false },
      { data: "projectId", title: "Project" },
      { data: "groupId", title: "Group" },
    ]

Is it possible to use the title directly from the labels I have defined in my schema with `collection2` instead of setting all the titles once again?

**Comment by aldeed** [comment]
The only way would be like this:

```
{ data: "projectId", title: mySchema.getDefinition("projectId", "label").label }
```
