### ISSUE TITLE
Why creating the global template filter TabularTables

### ISSUE THREAD

**Issue by mazing** [aldeed/meteor-tabular#234]
What is the advantage of populating the template with the variable `TabularTables` containing all tabular tables with a global template helper instead of just setting the option `table` directly in the tabular table?

**Comment by aldeed** [comment]
I'm not sure I understand this question, but if you're referring to using the `TabularTables` helper vs. keeping your own reference, it doesn't matter. You can do whichever you prefer.

If I'm not understanding, please post examples of the two approaches you're asking about.
