### ISSUE TITLE
Custom pub security strategy

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [aldeed/meteor-tabular#238]
Hi! thanks for the awesome package! I have a question, I would like to know the best practice to protect my app, lets say I have this custom pub that is being used by one of my Tabular Tables
```
Meteor.publishComposite('tabular_CargosList', function(tableName, ids, fields) {
  check(tableName, String);
  check(ids, Array);
  check(fields, Match.Optional(Object));
  this.unblock();
  return {
    find() {
      this.unblock();
      if (!this.userId || !Roles.userIsInRole(this.userId, ['admin', 'god'])) {
        return false;
      }

      return Cargos.find({_id: {$in: ids}}, {fields: fields});
    },
    children: [
      {
        find(cargo) {
          this.unblock();
          return Areas.find({_id: cargo.areaId}, { fields: { nome: 1}});
        },
      },
      {
        find(cargo) {
          return Carreiras.find({_id: cargo.carreiraId}, {fields: {nome: 1}});
        },
      },
    ],
  };
});
```

Let's say I have a field on the collection called "secret" and it must not be published to anyone
The logic to prevent people from subscribing to that secret field must be on the pub, right?
What about the allowFields on the Tabular instance?
I'm thinking that just by putting the logic inside allowFields, the pub will still be available to anyone who wants to see the secret field, by subscribing to it and passing the last parameter as {secret:1}

Could you guys help me out ?

Thanks!

**Comment by aldeed** [comment]
Correct, if you make your own publish function, you need your own security checks. The built-in security checks are only for the built-in publish functions.
