### ISSUE TITLE
If first column is 'tmpl:' type, Minimongo has a fit and throws an exception

### ISSUE THREAD

**Issue by ssteinerx** [aldeed/meteor-tabular#24]
![screenshot 2014-12-30 12 14 40](https://cloud.githubusercontent.com/assets/43063/5580769/9add2ccc-901d-11e4-9dcb-117b3d18f971.png)

**Comment by aldeed** [comment]
1.0 is released and should fix this. Please see updated [README](https://github.com/aldeed/meteor-tabular/blob/master/README.md) for all features and options.
