### ISSUE TITLE
How to pass parameters to publish function?

### ISSUE THREAD

**Issue by tab00** [aldeed/meteor-tabular#240]
Before using meteor-tabular this was my publish function:
```
Meteor.publish("PageItems", function (pageId) {
    check(pageId, String);

    return PageItems.find({ pageId: pageId });
});
```

To use meteor-tabular I changed it to:
```
Meteor.publish("Tabular_PageItems", function (tableName, ids, fields) {
  check(tableName, String);
  check(ids, Array);
  check(fields, Match.Optional(Object));

    return PageItems.find({ pageId: pageId });
});
```
However pageId would be undefined. So how can I pass pageId into the publish function in order to limit the results being subscribed to?

There doesn't seem to be any way to pass parameters when subscribing:
```
TabularTables.Pages = new Tabular.Table({
    name: "Pages",
    collection: Pages,
    pub: "Tabular_PageItems",
```

I know that it's possible to subscribe to the entire collection and filter on the client, however that would be a security risk and inefficient. Only what is needed by the client should be subscribed to and nothing more.

**Comment by rafaelcorreiapoli** [comment]
+1

**Comment by Cr1stal** [comment]
+1

**Comment by fipke** [comment]
+1

**Comment by allenfuller** [comment]
+1

**Comment by aldeed** [comment]
This is what the selector is for: https://github.com/aldeed/meteor-tabular#displaying-only-part-of-a-collections-data-set

**Comment by tab00** [comment]
I did see that but it's not clear, which is why I created this Issue in the first place.
Based on my understanding of using the selector, this is how the code should be:
```
Meteor.publish("Tabular_PageItems", function (tableName, ids, fields) {
  check(tableName, String);
  check(ids, Array);
  check(fields, Match.Optional(Object));

    return PageItems.find();
});
```
... and the selector in the constructor:
```
TabularTables.Pages = new Tabular.Table({
    name: "Pages",
    collection: Pages,
    pub: "Tabular_PageItems",
    selector: function (pageId) {
        return { pageId: pageId };
    },
```

Though since the filtering must be done on the server (not client-side), it's a little strange to see

```
    return PageItems.find();
```
in the publish function, as it appears that the entire collection is being published.

How or where exactly would the value of pageId be passed into the constructor so that only items of a particular page would be published from the server?

**Comment by aldeed** [comment]
@tab00 See description of what custom publish function must do in readme: https://github.com/aldeed/meteor-tabular#using-a-custom-publish-function

So `PageItems.find()` should be `PageItems.find({_id: {$in: ids}}, {fields: fields})`. But that's no different than the built in function so if you're not joining additional data, you probably don't need it.

It uses a two-step publication. The first one, which you can't customize, is what actually uses the selector. At that point we already have a list of IDs, which are passed into the second publish function, the one that can be customized if you need to join data.

The selector used by the first publish function is your client selector attribute + `selector` option on the table (for secure server selector), and then that is run through `changeSelector` function if there is one, for additional security.

**Comment by tab00** [comment]
I've just figured out that selector always takes the value of userId as it's input parameter value. The Readme documentation does not state such a fact, which has caused part of the confusion. e.g. if I wrote:

```javascript
    selector: function (x) {
        console.log("x", x);
        return { };
    },
```
the output would be the logged in user's ID.

So does this mean in the selector we cannot filter using any other field, and that what I wrote above is not possible?:
```javascript
selector: function (pageId) {
        return { pageId: pageId };
    },
```

Also, I should explain a bit more of what I have and want. I have 2 collections in a parent-child relationship: Pages, PageItems. Here are the schemas:
```javascript
    Schemas.Page = new SimpleSchema({
        userId: { ... },
        name: { ... },
        description: { ... },
        ...
```
```javascript
    Schemas.PageItem = new SimpleSchema({
        pageId: { ... },
        name: { ... },
        description: { ... },
```

In the Tabular table, I want to show a list of PageItem documents for a particular pageId value.
The value of pageId is taken from a dropdown list that contains a list of Pages that is filtered by userId.

This works fine without using Tabular, using this publish function:
```
Meteor.publish("pageItemsPage", function () {
    var cursorPages = Pages.find({ userId: this.userId });
    var pageIds = _.pluck(cursorPages.fetch(), "_id");
    var cursorPageItems = PageItems.find({ pageId: { $in: pageIds } });

    return [cursorPages, cursorPageItems];
});

```
Notice that the return value is an array of cursors, which makes it so easy, without needing to use publishComposite.


Another thing I would like to point out is that Your AppFeedBack example shows the use of Tabular with PublishComposite, with AppFeedBack being the parent collection and users the child, and, importantly, AppFeedBack field values being the data you want to show. Field values of the child collection displayed using helpers.

In my case, Pages is the parent, PageItems is the child, and I want to show PageItems field values in the table, not Pages field values. This is different to your example in which you show the parent collection's field values. So would I have to do these:

Write this publishComposite function:
```javascript
Meteor.publishComposite("tabular_Pages_PageItems", function (tableName, ids, fields) {
    check(tableName, String);
    check(ids, Array);
    check(fields, Match.Optional(Object));

    return {
        find: function () { return Pages.find({ _id: { $in: ids } }, { fields: fields }); },
        children: [
          {
              find: function (page) { return PageItems.find({ pageId: page._id }); }
          }
        ]
    };
});```

Set `collection: Pages` (instead of `collection: PageItems`) in the Tabular.Table constructor
```javascript
TabularTables.PageItems = new Tabular.Table({
    name: "PageItems",
    collection: Pages,
    pub: "tabular_Pages_PageItems",
    selector: function (userId) {
        return { userId: userId };
    },
    columns: [
      { data: "name", title: "Name" },
      { data: "description", title: "Description" },
      { data: "pageId", title: "pageId" },
```

... and then write a helper for each child collection field that I want to show as a table column? That would be extremely inconvenient. Is there any other way to show the field values of PageItems using `data:` in the columns array?

**Comment by aldeed** [comment]
@tab00 The problem is that you are trying to use the wrong selector. The `selector` table option is for limiting the selector on the server, like for security reasons. The `selector` attribute of your table template is for providing a reactive selector based on user choices on the client. So use the example at the top of this section: https://github.com/aldeed/meteor-tabular#displaying-only-part-of-a-collections-data-set But where it says `{author: "Agatha Christie"}` you would do `{pageId: userSelectedPageId.get()}` (assuming storing the selection in a `ReactiveVar` called `userSelectedPageId`), and then when drop down changes you would do `userSelectedPageId.set(idFromDropDown)`.

**Comment by tab00** [comment]
OK you are right, I need a client-side selector that is set based on the dropdown list value.

Can you also respond to my query about showing child collection field values instead of parent collection field values using Tabular? As I showed above, it was quite easy without Tabular using a publish function that returns an array of cursors.

**Comment by aldeed** [comment]
@tab00 I think you only need to flip the parent child in your example. Do `PageItems.find({ _id: { $in: ids } }, { fields: fields })` for the `find` and do `Pages.find({ _id: pageItem.pageId })` for the `children`. It does not matter that the "child" is actually the "parent".

**Comment by tab00** [comment]
If I set `collection: PageItems`, how would I use the server-side selector function for security which takes userId as input parameter? PageItems does not have a userId field. Pages does.

**Comment by tab00** [comment]
Switching Pages and PageItems in the publishComposite function works, however I'm also finding that executing `PageItems.find().fetch()` client-side returns all documents, including those of Pages of other users! That would be a security disaster.

When I remove `{{> tabular table=TabularTables...` from the template and use the publish function that I was using before (and shown again below), only the documents of the Pages of the logged-in user is returned as it should. So what's going wrong?

```javascript
Meteor.publish("pageItemsPage", function () {
    var cursorPages = Pages.find({ userId: this.userId });
    var pageIds = _.pluck(cursorPages.fetch(), "_id");
    var cursorPageItems = PageItems.find({ pageId: { $in: pageIds } });

    return [cursorPages, cursorPageItems];
});
```

**Comment by aldeed** [comment]
OK, I didn't know about the userId thing. The only way probably is to add `userId` to PageItems, too, and then do a server `selector` that does `{userId: this.userId}`.

**Comment by NazarYablonskiy** [comment]
Hey there!

I have some publication. eg following:
```
Meteor.publish('orders', () => {
  const transactionsIds = Transaction.find({success: true}).map(t => t._id);
  return Orders.find({transactionId: {$in: transactionsIds}})
});
```
I've tried to use `reywood:publish-composite`. It doesnt works for me - table doesn't displays the data.

How get it working with tabular?

looking forward for your answer :)

**Comment by maka-io** [comment]
@aldeed , I opened a new issue but it might be the same one that everyone here is experiencing. [#349](https://github.com/aldeed/meteor-tabular/issues/349)

Was there any resolution as to why the table doesn't display? (as @NazarYablonskiy stated)
