### ISSUE TITLE
How to separate each printed array element?

### ISSUE THREAD

**Issue by demiters** [aldeed/meteor-tabular#242]
I have a column of array type that currently prints 'element,second element,third element,etc' in the same table cell. However, I want better visual separation between the elements - one option could be applying different formatting to each comma separated element to differentiate between them, so I was wondering if it was possible to wrap each of the elements in the cell with a span tag. Or perhaps it's possible to change the element separator from comma to something else? Or put each element in its own cell altogether? Hope the question is clear.

**Comment by aldeed** [comment]
You can use a template or a render function for the column. Template would be something like:

```
<template name="cellTemplate">
  {{#each this.list}}
  <div>{{this}}</div>
  {{else}}
  None
  {{/each}}
</template>
```
