### ISSUE TITLE
Plugins support

### ISSUE THREAD

**Issue by ghost** [aldeed/meteor-tabular#243]
Hello! I have a problems with install plugins, after adding the bootstrap Select plugin, and all settings - its not worked. I move js files to compatibility and css move to stylesheets in client folder. All plugins already installed but not working.

**Comment by aldeed** [comment]
Can you post a link to the "bootstrap Select plugin"?

**Comment by crapthings** [comment]
fixHeader plugin works odd

    fixedHeader
        header: true
        headerOffset: 50

it doesn't work
