### ISSUE TITLE
Datatables with editor ?

### ISSUE THREAD

**Issue by sikreutz** [aldeed/meteor-tabular#248]
Has anybody managed to get datatables to work with the editor extension (https://editor.datatables.net/manual/getting-started)?

I am pretty new to Meteor and I am desperatly searching for a way integrate the editor. Simply including the js file and adding the  constructor:

```
var editor = new $.fn.dataTable.Editor( {} );
```

doesn't seem to do the trick. What else would I have to do to enable the editor?

Any help greatly appreciated!

Simon

**Comment by soclbz** [comment]
@sikreutz, did you get this working? I'm also stuck in this issue. 
@aldeed can you please help here...
