### ISSUE TITLE
Problem including tabular in a package

### ISSUE THREAD

**Issue by Garbolino** [aldeed/meteor-tabular#255]
I'm building a package where I want to use meteor-tabular to display data. Everything seems to be working right but the 'tmpl' feature. It does not show up the template.
In my package settings I have: api.use('aldeed:tabular') and api.imply('aldeed:tabular').
Any idea?
Thank you

**Comment by aldeed** [comment]
Make sure to use `aldeed:tabular@1.5.1` so that the latest version is used. If it still does not work, you would have to link to a repo with an app that reproduces this.

**Comment by Garbolino** [comment]
Thank you aldeed for your response, I made sure to use 1.5.1 version and I still have same problem.
I have uploaded a repository with an example of how I want to use tabular package.
https://github.com/Garbolino/test-packages

I'm building the package meteor-proxys located in packages folder where I use tabular. I have deployed it here: http://test-meteor-proxys.meteor.com/ you can login with: admin@example.com / 111111 last columns in both tables use 'tmpl' feature.

Thank you for helping

**Comment by aldeed** [comment]
Hi @Garbolino,

Thank you for the reproduction. Move this block to be the last `addFiles` block in your package.js. The template files need to be added first otherwise Template.whatever is undefined when your table definition is run.

```js
api.addFiles([
    'both/proxys-packages.coffee',
    'both/proxys.coffee',
    'both/proxys-tabular.coffee'
  ],['client', 'server']);
```

**Comment by Garbolino** [comment]
It works, thank you for you help!
