### ISSUE TITLE
Buttons/Export functionality working?

### ISSUE THREAD

**Issue by fdddk23** [aldeed/meteor-tabular#256]
Hi,

How can I enable CSV Export functionality for tabular like it is available for DataTables?
Like https://datatables.net/extensions/buttons/examples/initialisation/export.html

How is the best way to achieve this with DataTables?

**Comment by aldeed** [comment]
Unless your collection size is very small, I don't think you can use DT CSV because I believe it only works with data on the client, whereas this package uses server-side data. You'd have to use an npm package to generate CSV on the server and allow client to download it.
