### ISSUE TITLE
mysql collection

### ISSUE THREAD

**Issue by philaphil** [aldeed/meteor-tabular#267]
Hi,
I am very new to meteor and I am trying to get a MySql select to put the results into a meteor-tabular

When I try to use numtel:mysql I keep getting an
Error: Tabular.Table options must specify collection
wBooks = new MysqlSubscription("theBooks");

When I switch to mongo.collection everything works
wBooks = new Mongo.Collection("theBooks");

This is my MySQL
  Meteor.publish('theBooks', function() {
    return liveDb.select(
                  'SELECT'
                +'   `title`'
                +' , `author`'
                +' , `url`'
                +' FROM `ZBooks`',
                  [ { table: '`ZBooks`' } ]
    );
  });

**Comment by aldeed** [comment]
Closing old issues.
