### ISSUE TITLE
Memory leak due to non-destruction

### ISSUE THREAD

**Issue by Miges** [aldeed/meteor-tabular#271]
It appears that the datatable initialised never has its `destroy()` (https://datatables.net/reference/api/destroy%28%29) method called.  This appears to be causing a memory leak.

Here are some graphs showing the memory (and other things as well) usage in chrome of tabular with and without a call to `destroy()`.  The 'dips' are forced garbage collections - as can be seen in the case without the call to `destroy()` the un-collectable memory allocations are climbing.
### without destroy (as it is now)

![without destroy](https://cloud.githubusercontent.com/assets/6656116/13040387/61453294-d3e6-11e5-8f72-db4c53699bfe.png)
### with destroy

![with destroy](https://cloud.githubusercontent.com/assets/6656116/13040386/5d380bb8-d3e6-11e5-8f27-865c92d4d22c.png)

The app used to make these graphs is here:  https://github.com/Miges/tabular-memory-leak

I am unsure why the node count is still climbing.

**Comment by lynchem** [comment]
Thanks a lot @Miges . I tested this and also noticed memory increasing steadily on the client. I added the destroy call to all of my template.onDestroyed functions where I used a tabular table and problem solved (although would probably have been quicker to just for it). Would be good to get this fix into a release soon.

**Comment by praveenkoka** [comment]
@Miges @lynchem I'm having a memory leak issue as well. The memory, nodes, and event listeners increase as I switch between pages. How would you suggest I call the destroy function to prevent this while switching pages. Thanks.

**Comment by lynchem** [comment]
I've done this in all the templates where I have created a tabular table. 
```
Template.yourTemplate.onDestroyed(function() {
    $("your-tabular-table-id").DataTable().destroy();
});
```

**Comment by aldeed** [comment]
v2.0.1 destroys the DT. It would be nice if anyone can confirm that this works in your particular situations.
