### ISSUE TITLE
How to limiting data on server side?

### ISSUE THREAD

**Issue by radiegtya** [aldeed/meteor-tabular#273]
How to limiting data on server side that is trigerred from client side?
Because I think publishing all data without limit is not a good thing when data have thousand or more record.

Here is my server

```
/*
i wanna set the doc and sortLimit parameter from client side reactively, so that the published data is limited
*/
Meteor.publish('models', function(doc, sortLimit){
    var doc = doc || {};
    var sortLimit = sortLimit || {}; 

    return Models.find(doc, sortLimit);
});
```

Here is my client

```
Template.modelsIndex.onCreated(function(){
    var self = this;
    self.autorun(function() {
        //so in client i can use reactiveDoc and reactiveSortLimit to subscribe my collections from server
        self.subscribe('models', reactiveDoc, reactiveSortLimit);
    });
});
```

How to do that? because Tabular.Selector and Tabular.changeSelector is not what I needed.

**Comment by gibex** [comment]
Try a  "Custom Publish Function" section, Tabular has it's own publication type.
