### ISSUE TITLE
Data not reacting to removals (?)

### ISSUE THREAD

**Issue by csillag** [aldeed/meteor-tabular#277]
What am I missing?
- Created a meteor project.
- Added the following packages:  `aldeed:tabular`, `twbs:bootstrap`, `fortawesome:fontawesome`
- Added HTML code:

``` HTML
<body>
  <h1>Tabular test</h1>
  {{> tabular table=TabularTables.Users class="table table-striped table-bordered table-condensed"}}
</body>

<template name="userActionsCell">
    <button type="button" class="btn btn-xs delete btn-danger fa-remove"></button>
</template>
```
- Added JS code:

``` JavaScript
Users = new Mongo.Collection("users");

TabularTables = {};

TabularTables.Users = new Tabular.Table({
    name: "Users",
    collection: Users,
    columns: [
        {data: 'firstName', title: 'First name'},
        {data: 'lastName', title: 'Last name'},
        {data: 'email', title: 'E-Mail'},
        {tmpl: Meteor.isClient && Template.userActionsCell, title:'Actions'}
    ]
});

if (Meteor.isClient) {
  Template.userActionsCell.events({
    'click .delete': function () {
      if (window.confirm("Should we really delete this user?")) {
        Users.remove(this._id);
      }
    }
  });
}

```
- Added some data to the MongoDB table.
  ---

The app works, but the table does not react to data changes.

I can delete records using the built-in functionality, or I can add/delete/modify
data on the meteor console directly, but the changes are not reflected
on the UI, if I don't reload the application.

What am I doing wrong?

Thank you for explaining.

**Comment by PankajJatav** [comment]
Set "responsive: true" in your TabularTables.Users Instance. like this...
```
TabularTables.Users = new Tabular.Table({
    name: "Users",
    collection: Users,
    columns: [
        {data: 'firstName', title: 'First name'},
        {data: 'lastName', title: 'Last name'},
        {data: 'email', title: 'E-Mail'},
        {tmpl: Meteor.isClient && Template.userActionsCell, title:'Actions'}
    ],
    responsive: true,
});
```

**Comment by csillag** [comment]
> Set "responsive: true" in your TabularTables.Users Instance

I tried, but it doesn't make a difference.

Furthermore, from the docs, I guess that "reponsive" is more about mobile devices, then about data reactivity... but I might be wrong about this.

**Comment by PankajJatav** [comment]
Hi @csillag ,
It will be great if you can share your code with me.
So I can look into your code and resolve the issue.

**Comment by csillag** [comment]
I published the minimal test case here: 

https://github.com/csillag/tabular-test

You can just add some data manually to the database like this:

```
meteor mongo
db.users.insert({firstName: "test", lastName: "user", email: "x@y.z"});
```

Contrary to my earlier report, this update **will** be reflected on the UI.
However, if I do:

```
meteor mongo
db.users.remove({});
```

then the UI won't be updated.
(The same happens when I remove individual records.)

So the widget is *somewhat* reactive; additions appear, but removal don't. (Not sure about updates, but if removals are broken, then it's all the same.)

**Comment by csillag** [comment]
I edited the title to reflect the observation that adding records works, only removal seems to be broken.

**Comment by PankajJatav** [comment]
Hi @csillag,
The code is working fine.
Instead of try to insert data from mongo shell, Insert data from browser console.
like: Users.insert({firstName: "test", lastName: "user", email: "x@y.z"});
It look like issue occurring because of mongodb user object ID as _id where as meteor create 16 hex string for _id.But I am not quite sure of why its happening.

**Comment by PankajJatav** [comment]
In case of any query feel free to mail me.

**Comment by csillag** [comment]
Normally I receive the reactive updates to the data on client side, when I
delete record on the mongo console on the server side.

I can display those updates just fine with other client-side widgets, it's
just this component that doesn't get updated.

**Comment by csillag** [comment]
As I said, insert always works.
Delete doesn't.

**Comment by csillag** [comment]
So, in short, this still seems to be a bug for me.

**Comment by ivan133** [comment]
I can confirm - doesn't update with native mongoId.
In my case I'm updating entity not deleting it.
I've checked with browser dev console - collection find() returns empty sequence.
I guess data remains only in DOM.
@csillag Can you check collection find() returns an empty sequence too?

**Comment by UnforeseenSoftware** [comment]
I have the same issue. To work around the issue, I wrap the tabular template in a {{#if volatileData}} helper which forces the table to refetch/render. This will only help the current user. Other clients will not see the change until navigating away and back, so this is a bug. Here is some stripped down code for the work around.
```html
    {{#if volatileDataReady}}
        {{> tabular table=table selector=selector}}
    {{else}}
        {{> spinner}}
    {{/if}}
```
```javascript
VOLATILE_DATA_READY = 'volatile_data_ready';
UI.registerHelper('volatileDataReady', function () {
    // this gets triggered when an operation causes a MongoDB change
    // The contained templates will be forced to reload/rerender
    if (Session.get(VOLATILE_DATA_READY)) {
        Meteor.defer(function () {
            Session.set(VOLATILE_DATA_READY, null);
        });
        return false;
    }
    return true; // default is true
});

Template.deleteTableCellTemplate.events({
    'click .delete-item': function (e) {
        var dataset = e.target.dataset;
        Meteor.call(deleteFunc, { data: e.target.dataset['data'] },
            function (error, result) {
               if (error) {
                  logger.debug(error);
               } else if (result) {
                  logger.debug(result);
                  // Notify table wrapper to force refresh
                  Session.set(VOLATILE_DATA_READY, true);
               }
        });
    }
});
```

**Comment by ivan133** [comment]
Guys! 
I think I fixed this issue.
https://github.com/aldeed/meteor-tabular/pull/293

**Comment by dancastellon** [comment]
+1 for ivan133's PR. I'm using Mongo IDs and currently removals aren't reactively updating the table (i.e. removing the row)
