### ISSUE TITLE
Glyphicons Reference Issue

### ISSUE THREAD

**Issue by arist0tl3** [aldeed/meteor-tabular#279]
Just updated from ~1.4 to the latest and started seeing:

`OTS parsing error: invalid version tag
projects:1 Failed to decode downloaded font: http://localhost:3030/fonts/glyphicons-halflings-regular.woff`

We are using a less version of bootstrap 3. Just curious if anyone else is running into this or has an idea about a fix?

**Comment by aldeed** [comment]
Closing old issues

**Comment by anthonymanzo** [comment]
Hey
I have the same issue, was there ever a solution?
