### ISSUE TITLE
How to get tables records count in other template?

### ISSUE THREAD

**Issue by alexpyslar** [aldeed/meteor-tabular#280]
Hello, have next situation: made table in collection and output it with {{> tabular table=TabularTables.Posts selector=selector class="table table-striped table-bordered table-condensed"}}
It's a tab and I want to show table records count on the tab head (instead of title), question is, how to fetch this count?

**Comment by aldeed** [comment]
I think something like this might work:

```js
const count = $('table').DataTable().ajax.json().recordsTotal;
```

It would not be reactive so you'd have to call it repeatedly on an interval.
