### ISSUE TITLE
Stuck "Processing..." pop-up *without* Bootstrap, caused by commit 8e7b14d33354f7

### ISSUE THREAD

**Issue by domq** [aldeed/meteor-tabular#282]
1. Create sample Meteor app from the [example in the README.md](https://github.com/aldeed/meteor-tabular#example), fixing the obvious (i.e. `Books = new Mongo.Collection("Books");`)
2. Run app
3. Click on any column header

The "Processing..." pop-up shows up, and freezes (see screenshot)

Happens even on an empty table, and regardless of whether `tmpl` is in use in the columns.

`git bisect` gives 8e7b14d33354f7 as the culprit.

This is related to, but different from issue #281 (different results from `git bisect`)

![Screenshot](https://cloud.githubusercontent.com/assets/1629585/13547114/ac196974-e2c4-11e5-9e99-d94d0ab346ea.png)

**Comment by domq** [comment]
`git revert 8e7b14d` on today's `master` fixes the issue (after solving a trivial conflict)

**Comment by domq** [comment]
Silly patch below "fixes" it, as well as #281

<pre>
diff --git a/client/tabular.js b/client/tabular.js
index 8894a9f..cd347fd 100644
--- a/client/tabular.js
+++ b/client/tabular.js
@@ -356,7 +356,7 @@ var tabularOnRendered = function () {
       }
     }
 
-    template.tabular.isLoading.set(false);
+    // template.tabular.isLoading.set(false);
   });
</pre>

**Comment by aldeed** [comment]
Should be fixed in 2.0
