### ISSUE TITLE
ReferenceError with FS.Collection

### ISSUE THREAD

**Issue by Achtel** [aldeed/meteor-tabular#285]
Hi guys, I'm getting the same error as outlined in #68 but both my table definition (documentTable.js) and its associated collection (images_documents.js) are in the same location:

|-collections
|--documentTable.js
|--images_documents.js

It may be worth noting that the Documents collection is a FS.Collection... 

```
Documents = new FS.Collection("Documents", {
    stores: [docStore],
    filter: {
      allow: {
        contentTypes: ['application/pdf']
      }
    }
  });

```

Would this affect anything? The error I get is ReferenceError: Documents is not defined at collections/documentTable.js:5:15.

```
TabularTables.Documents = new Tabular.Table({
  name: "Documents",
  collection: Documents,
  columns: [
    {data: "_id", title: "ID"},
    {data: "original.name", title: "Name"},
    {data: "userId", title: "User ID"},
    {
      tmpl: Meteor.isClient && Template.documentTable
    }
  ]
});

```

**Comment by Achtel** [comment]
I've tried referencing it as cfs.Documents.filerecord as well (which is how it shows up in Mongol), but unsuccessfully so.

**Comment by H1net** [comment]
Same.

**Comment by H1net** [comment]
Resolved my issue by declaring Tabular outside of client. i.e not in the client folder.
