### ISSUE TITLE
Need for one example using Angular

### ISSUE THREAD

**Issue by numero8** [aldeed/meteor-tabular#288]
Current documentation and examples are very clear for a newcomer wanting to use Tabular in his project. However, a short example illustrating the use of Tabular in a Meteor+Angular configuration would save a lot of investigation time.

Many thanks for your work!

**Comment by aldeed** [comment]
Closing old issues

**Comment by promentol** [comment]
The solution will be to use embedded Blaze template in Angular. 
Here is a link for documentation
https://angular-meteor.com/api/angular-meteor/1.3.11/blaze-template
