### ISSUE TITLE
Dynamic number of columns in a Table

### ISSUE THREAD

**Issue by kantle** [aldeed/meteor-tabular#289]
Love working with the Tabular package - it's been great.
Working on one use case that is appearing a bit tricky, where I need to have a dynamic number of columns within the table.

Basically my app consists of projects, where each project has different questions, and each question has responses. Based on the route a user is at  (e.g. projects/this-is-an-example-project), it loads a table for that project, where the columns need to be each of the questions in the project, and the rows need to be each users set of responses to those questions.

The challenge is that since each project has an unknown number of questions, I wouldn't know the number of columns at startup. As a user navigates to a new route. I'd need to dynamically add columns based the number of questions that are in that project. I can see how I would do this if I knew the route at startup (I'd just push a new column for every question in the project), but since the number of questions would change depending on the route, I'd need a way to dynamically change the TabularTable definition.

This might be outside of the intended use for this package but I wanted to check first? I'd love to keep the benefits of the package (e.g. paginated subscriptions).

Thanks!

**Comment by bpartridge** [comment]
While you can't make table definitions dynamic, you can switch the table instance that a template renders, so if you have a finite set of definitions, you can choose which one reactively. This isn't officially supported, and the biggest blocker is that sometimes code is called with a mix of parameters from the old and new definitions. We were able to work around by forking and catching errors in `Util.getMongoSort` (see https://github.com/belstone/meteor-tabular/commit/18cac4faafd07c580d1a5441873c689b9d357855), and by making sure we catch errors in any `createRow` callbacks. It's not pretty, certainly not PR-worthy, but it works.

**Comment by aldeed** [comment]
Column overrides could be added as a feature. I believe there is another issue existing for it.
