### ISSUE TITLE
Question: Turning off / deactivating the cache...

### ISSUE THREAD

**Issue by boustanihani** [aldeed/meteor-tabular#29]
Is there a way to deactivate / turn off the cache when a table is no longer needed ?

**Comment by aldeed** [comment]
1.0 is released and should fix this. Please see updated [README](https://github.com/aldeed/meteor-tabular/blob/master/README.md) for all features and options. Particularly note the section about data caching. Nothing is cached by default now, so when the template containing your table is destroyed, the data will disappear from the client.
