### ISSUE TITLE
Started getting "Error: Can't wait without a fiber"

### ISSUE THREAD

**Issue by maxko87** [aldeed/meteor-tabular#291]
This error just started happening as of yesterday. Any ideas?

``Error: Can't wait without a fiber ``
``at Function.wait (/app/build/bundle/programs/server/node_modules/fibers/future.js:155:9) ``
``at Object.Future.wait (/app/build/bundle/programs/server/node_modules/fibers/future.js:397:10) ``
``at [object Object]._.extend.count (packages/mongo/mongo_driver.js:1059:1) ``
``at [object Object].Cursor.(anonymous function) (packages/mongo/mongo_driver.js:869:1) ``
``at [object Object].cursorProto.(anonymous function) (packages/meteorhacks_kadira/lib/hijack/db.js:126:1) ``
``at [object Object].kadira_Cursor_count [as count] (packages/meteorhacks_kadira/lib/hijack/set_labels.js:81:1) ``
``at updateRecords (packages/aldeed_tabular/server/tabular.js:118:1)``
``at updateRecords (packages/aldeed_tabular/server/tabular.js:118:1) ``
``at [object Object].later [as _onTimeout] (packages/underscore/underscore.js:695:1) ``
``at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)  ``

**Comment by KudMath** [comment]
@maxko87 did you find wha was causing this? I'm getting a similar error.
