### ISSUE TITLE
Highlight the data as per value

### ISSUE THREAD

**Issue by ivandgreat** [aldeed/meteor-tabular#292]
Good day..

After defining my table as per example

TabularTables = {};

TabularTables.Books = new Tabular.Table({
 ....
 ....
});

and add a reference on my template

{{> tabular table=TabularTables.Books class="table table-striped table-bordered table-condensed"}}

How could i able to implement the class label as per cell value?

{{#if priorityActive}}
  <span class="label label-danger">{{priority}}</span>
{{/if}}

br,

**Comment by aldeed** [comment]
Closing old issues
