### ISSUE TITLE
Issue in Meteor 1.3: Unable to resolve some modules"

### ISSUE THREAD

**Issue by allenfuller** [aldeed/meteor-tabular#299]
Upon upgrading to Meteor 1.3, I get the following message when loading my app:

```
Unable to resolve some modules:

  "datatables.net" in /<app root>/client/js/dataTables.select.js (web.browser)
  "datatables.net-bs" in /<app root>/client/js/responsive.bootstrap.js (web.browser)
  "datatables.net-buttons" in /<app root>/client/js/buttons.print.js (web.browser)
  "datatables.net-responsive" in /<app root>/client/js/responsive.bootstrap.js (web.browser)

Consider running: meteor npm install --save datatables.net datatables.net-bs datatables.net-buttons datatables.net-responsive
```

These are all files I've added from dataTables.net directly to add bootstrap and button functionality.

It appears the recommended path is to drop Tabular and go with the NPM version of DataTables, but I'm very hesitant to do that due to all of the work @aldeed has put into this package to make DataTables work better for Meteor.

Is anyone else having this issue, and what steps are you taking to migrate or stay?

**Comment by allenfuller** [comment]
I should note that this wouldn't be an issue, except that now buttons do not appear on my app's datatable.

**Comment by dovrosenberg** [comment]
Similar issue here but with DataTables extensions placed in client/compatibility.  Work fine with Meteor 1.3, but if I add the modules package, they throw errors because they `require()` jquery and datatables which haven't been added via npm.  Unlike @allenfuller's scenario, in this case, it actually breaks the app.

**Comment by allenfuller** [comment]
Having researched this a bit further, it appears the issue is related to Meteor 1.3's `modules` package and how it relates to CommonJS `module.exports`. That doesn't help with a resolution, but at least hopefully narrows it down a bit.

**Comment by dovrosenberg** [comment]
Not sure if this will help @allenfuller, but I've solved my issue.  I had installed a couple Datatables plugins in /client/compatibility.  Each of those plugins had code that looked like:

```javascript
// Define as an AMD module if possible
if ( typeof define === 'function' && define.amd ) {
	define( ['jquery', 'datatables'], factory );
}
else if ( typeof exports === 'object' ) {
    // Node/CommonJS
    factory( require('jquery'), require('datatables') );
}
else if ( jQuery && !jQuery.fn.dataTable.ColReorder ) {
	// Otherwise simply initialise as normal, stopping multiple evaluation
	factory( jQuery, jQuery.fn.dataTable );
}
```
where ColReorder is the name of the particular plugin.

I commented all of that out and replaced it with just:
```javascript
if ( jQuery && !jQuery.fn.dataTable.ColReorder ) {
	// Otherwise simply initialise as normal, stopping multiple evaluation
	factory( jQuery, jQuery.fn.dataTable );
}
```

The code now builds and runs successfully under 1.3.1 (and 1.3, I assume), even with the modules package installed.

**Comment by H1net** [comment]
Same issue. Above works for ColReorder, but does not seem to solve with all plugins. I am having trouble getting the basic buttons plugin to work again.

**Comment by DataTables** [comment]
Hi - DataTables author here. I had someone interested in this topic point me to this issue and I'm wondering if I can help out at all. Does anyone know how meteor handles the `require`? Does it parse and execute the code as Javascript, or is it doing string matching to find the `require` commands?

**Comment by mpkliewer** [comment]
I got the Tabular package to work with **Meteor 1.3.2.4** using imports and current Meteor Guide recommended folder structure. 

(I was able to get DataTables to work by itself with NPM and `require( 'datatables.net' )()`, etc. but I wanted to easily grab Mongo data with this package.)

In my app for example, I have a table where I need to show _Reservations_ from MongoDB:

#### Create Tabular.Table and export
**/imports/api/reservations/tables.js**
```javascript
import { Tabular } from 'meteor/aldeed:tabular';
import { Reservations } from '/imports/api/reservations/add-new';

const TabularTables = {};

TabularTables.Reservations = new Tabular.Table({
  name: "Reservations",
  collection: Reservations,
  columns: [
    {data: "startTime", title: "Date"},
    // etc.....
  ]
});

export { TabularTables };
```

#### Import table to run on server
**/imports/api/reservations/server/publications.js**
```javascript
// import "common code"
import { TabularTables } from '/imports/api/reservations/tables.js';
// (Tabular is handling publications automatically)
// any other publications can live here as normal
```

#### Import HTML and table to run on client
**/imports/ui/pages/reservations/manage/manage.js**
```javascript
import './manage.html';
import { TabularTables } from '/imports/api/reservations/tables.js';
// (Tabular is handling subscriptions automatically)
// remainder of normal Blaze template logic
```

#### Add to Blaze template
**/imports/ui/pages/reservations/manage/manage.html**
```javascript
<template name="reservationsManage">
  {{> tabular table=TabularTables.Reservations class="table table-striped table-bordered table-condensed"}}
</template>
```

**Comment by timmakken** [comment]
First of all sorry for not being related to this specific package but my findings might help people debug this package faster.

When i add the downloaded bundle from datatables.net and add it to my client/plugins folder i got similar issues. My fix to get the buttons working was removing the ecmascript package.
running meteor 1.3.x.  its not a good solution but at least the export buttons are working for me.

Great work once again @aldeed on this package. il keep checking and when the export buttons are working i will switch to your package instead of the static lib.

**Comment by aldeed** [comment]
v2 should be fully compatible with 1.3+ (although I never personally saw these errors with v1 on 1.3)
