### ISSUE TITLE
problem with more then one of Tabular file?

### ISSUE THREAD

**Issue by yuomtheara** [aldeed/meteor-tabular#30]
I have 2 `tabular file`,
```
// Book.js
TabularTables = {};
Meteor.isClient && Template.registerHelper('TabularTables', TabularTables);
TabularTables.Books = new Tabular.Table({
    name: "BookList",
    collection: Books,
    columns: [
        {data: "title", title: "Title"},
        {data: "author", title: "Author"},
        {data: "copies", title: "Copies Available"},
................

// Classes.js
TabularTables = {};
Meteor.isClient && Template.registerHelper('TabularTables', TabularTables);
TabularTables.Classes = new Tabular.Table({
............
```
it don't show anything.

**Comment by whileoneloop** [comment]
Don't repeat the initialization of TabularTables, or you will wipe out your previous configuration.

Your top two lines are not necessary in your subsequent files.

If you do want to repeat the top line, to make sure it has been declared before using it, change to this:

TabularTables = TabularTables || {};

**Comment by yuomtheara** [comment]
I should be use `TabularTables = TabularTables || {};` on any file tabular or not?

**Comment by whileoneloop** [comment]
Just use at the top of files which you are wanting to define entries for TabularTables .

Regards,
Tim

**Comment by yuomtheara** [comment]
thanks.
