### ISSUE TITLE
fails for multi user dynamic columns

### ISSUE THREAD

**Issue by interfaith** [aldeed/meteor-tabular#310]
a solution for varying columns ?

user1 puts color/time into collection x
user 2 puts age/height into collection x

this and others like it totally collapse here for multi user /dynamic columns

a solution that 1. allows several users with varying columns
AND 2. indexing on a queryId IS needed

hopefully jquery datatables will do it
https://github.com/ephemer/meteor-reactive-datatables

**Comment by luixal** [comment]
Also looking for this.

**Comment by aldeed** [comment]
Closing this since I don't understand what the request is. An example of what you want to do would help.
