### ISSUE TITLE
Using on Meteor 1.3.2.4

### ISSUE THREAD

**Issue by ickyrr** [aldeed/meteor-tabular#314]
Hi, @aldeed, do you have an example of how to use this on a Meteor 1.3 app? I follow your example on the README, but I can't get it to work. Here's the error i'm getting.

```
Exception from Tracker afterFlush function:
debug.js:41 ReferenceError: Session is not defined
    at tabular.js:270
    at Object.Tracker.nonreactive (tracker.js:589)
    at .<anonymous> (tabular.js:269)
    at view.js:199
    at Function.Template._withTemplateInstanceFunc (template.js:465)
    at view.js:197
    at Object.Blaze._withCurrentView (view.js:538)
    at viewAutorun (view.js:196)
    at Tracker.Computation._compute (tracker.js:323)
    at new Tracker.Computation (tracker.js:211)
```

Thanks in advance!

**Comment by thearabbit** [comment]
I would like to have example for Meteor 1.3 too.
Please...

**Comment by pmoulos** [comment]
@ickyrr @thearabbit Have you downloaded the session atmosphere package into your project? At least for me, it was not included in the standard meteor installation.

`meteor add session`

**Comment by thearabbit** [comment]
Excuse me, could you example file structure for `Tabular`
```js
imports/
   api/
.........
```
Where for `Tabular`, and should be autoload or not?

**Comment by pmoulos** [comment]
@thearabbit I think that @aldeed could put some effort in refactoring/restructuring `Tabular` (please do so, it's one of the greatest packages ever!) in order to properly work with Meteor 1.3 which I believe does not really 'like' common code and `/lib` directory.

What I am doing at this point is to structure my current application as suggested by MDG in the [meteor guide](http://guide.meteor.com/) and the [todos](https://github.com/meteor/todos) application. I use `/lib` only for `Tabular` as follows:

I have a `init-tables.js` file which simply exports the `TabularTables` variable as in aldeed's instructions.

```
export let TabularTables = {};
Meteor.isClient && Template.registerHelper('TabularTables',TabularTables);
```

Then I have some .js files that define the tables and import any necessary information from the client (e.g. templates to be used in table cells) using `require`. For example, the following is a chunk from `hometables.js`:

```
// Import meteor stuff
import { Template } from 'meteor/templating';

// Import npm stuff
import moment from 'moment';

// Import TabularTables helper
import { TabularTables } from './init-tables.js';

// Import my stuff
import { Projects } from '../imports/api/project/projects.js';

// Import stuff form client needed for table rendering (remember that we are at /lib)
if (Meteor.isClient) {
    require('../imports/ui/pages/home/home-project-action.html');
    require('../imports/ui/pages/home/home-project-status.html');
}

TabularTables.Projects = new Tabular.Table({
    name: "Projects",
    collection: Projects,
    extraFields: ['date_accessed'],
    columns: [{
        data: "title", 
        title: "Title"
    },{
        data: "date_accessed",
        title: "Date accessed",
        render: function(val,type,doc) {
            return moment(val).format("MMM D, YYYY HH:mm");
        }
    },{
        data: "status", 
        title: "Status",
        tmpl: Meteor.isClient && Template.homeProjectStatus
    },{
        title: "Action",
        tmpl: Meteor.isClient && Template.homeProjectAction
    }],
    order: [[1,'desc']],
    autoWidth: false,
    processing: true,
    dom: '<"pull-left"f><"pull-right"p>rti',
    columnDefs: [{ 
        "width": "45%", 
        "targets": 0
    },{ 
        "width": "30%", 
        "targets": 1
    },{ 
        "width": "10%", 
        "targets": 2
    },{ 
        "width": "15%",
        "targets": 3
    }]
});

```
So the structure would be:

```
imports/
  /api
  ....
lib/
  init-tables.js
  hometables.js
```
It works for me so far.

**Comment by thearabbit** [comment]
Thanks for your reply.
It work fine for above structure.
but my structure is `module in imports folder`
```js
imports/
   modules/
       foo/...
       bar/...
```

**Comment by tetiogit** [comment]
I'm approaching the same issue. It seems to work as follows:
1 - define your `TabularTables` in the `imports/api` folder, say `tabular.js`
2 - recall `tabular.js` from `startup/server/registerApi.js` or the equivalent `main.js` file launched on startup of the server
3 - I've still not investigated the issue of `registerHelper` but it was an headache too also on previous meteor verions

hope it helps

**Comment by thearabbit** [comment]
Thanks, It work fine when I startup `Tabular` in `main.js` out of `imports folder`.

**Comment by jdnichollsc** [comment]
Hi guys! Exist any example? I'm getting the following error:

```
W20161204-11:50:50.145(-5)? (STDERR) C:\Users\juan.nicholls\AppData\Local\.meteor\packages\meteor-tool\1.4.2_3\mt-os.
windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:280
W20161204-11:50:50.146(-5)? (STDERR)                                            throw(ex);
W20161204-11:50:50.147(-5)? (STDERR)                                            ^
W20161204-11:50:50.147(-5)? (STDERR)
W20161204-11:50:50.148(-5)? (STDERR) TypeError: Tabular.Table is not a function
W20161204-11:50:50.149(-5)? (STDERR)     at meteorInstall.lib.dataTables.contracts.tables.js (lib/dataTables/contract
s/tables.js:9:27)
W20161204-11:50:50.149(-5)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:181:9)
W20161204-11:50:50.150(-5)? (STDERR)     at require (packages\modules-runtime.js:106:16)
```

Regards, Nicholls

**Comment by thearabbit** [comment]
you try to add `Tabular` out of `imports`.
```js
common/
   Tabular.js
imports/
   ...
```

**Comment by jdnichollsc** [comment]
Very odd... removing some packages and moving the reference from **packages** file works! xD

**Comment by thearabbit** [comment]
what packages?

**Comment by jdnichollsc** [comment]
Sorry man, I don't remember, but it's very important to review all packages and remove the unnecesary packages, to avoid conflicts :)
