### ISSUE TITLE
Button showing under a condition

### ISSUE THREAD

**Issue by albertorepo** [aldeed/meteor-tabular#316]
Hi Folks, 
I would need to add a condition when I show the Template of a button.
Right now, I have something like this:
        {
            data: 'name',
            title: 'Name'
        },
        {
            tmpl: Meteor.isClient && Template.checkOut
        }
So now I need that the Template 'checkOut' to only be visible when another column takes a particular value, i.e., when 'name' is 'John'.
How can I achieve this?

**Comment by luixal** [comment]
This would also be shown if `visible` would accept a function as value. Similar case to #284 , same solution for both and other many issues.

**Comment by aldeed** [comment]
You template could have `{{#if otherColumnEqualsWhatever}}` helper around the button. All column values for that row are available in the cell template.
