### ISSUE TITLE
Set column order

### ISSUE THREAD

**Issue by rhsu0268** [aldeed/meteor-tabular#319]
Hi, 

I would like to set the column order for the tabular table. Is there a way to do that?

Many thanks,
Richard

**Comment by metalik** [comment]
Try use the "order" option from datatable (https://datatables.net/examples/basic_init/table_sorting.html) but failed.

```javascript
const FooTable = new Tabular.Table({
  name: 'FooTable',
  collection: Foo,
  order: [[0, 'asc']],
  columns: [
.
.
.
.

```

**Comment by aldeed** [comment]
The columns are in the order you define them in the array. Just define them in a different order.

**Comment by Silverutm** [comment]
try
columns: [],
order: [[0, 'asc']]
