### ISSUE TITLE
how to get  value of other field in custome field?

### ISSUE THREAD

**Issue by yuomtheara** [aldeed/meteor-tabular#32]
I would like custome field value with other field value like this:
```js
....
{data: "copies", title: "Copies Available"},
    {
      data: "lastCheckedOut",
      title: "Last Checkout",
      render: function (val, type, doc) {
        if (val instanceof Date) {
          return moment(val).calendar();
        } else {
          // how to get copies field value?
          return copies.value;
        }
      }
    },
....
```

**Comment by aldeed** [comment]
I do this by using the `dburles:collection-helpers` package to add a `lastCheckedOut` helper set to your render function, and then change your "lastCheckedOut" to "lastCheckedOut()", which will call the helper function.

**Comment by yuomtheara** [comment]
how to get `copies` value in the `lastCheckedOut` custom field?

**Comment by aldeed** [comment]
`doc.copies`? Your question isn't related to this package, so you should be able to find the answer in the [DataTables documentation](http://datatables.net/reference/option/columns.render).

**Comment by yuomtheara** [comment]
very thank.
