### ISSUE TITLE
Possible to re-initialize the table with different parameter?

### ISSUE THREAD

**Issue by hhsiao** [aldeed/meteor-tabular#322]
I have need to re-initialize the table with different columnDef, I can't seems to figure out how this can be done.  Any help is greatly appreciated.

**Comment by felipesmendes** [comment]
Similar case to #284

**Comment by aldeed** [comment]
This isn't easy so I think it would be better for someone to submit an issue explaining what you are actually trying to achieve (why you want to update columns).
