### ISSUE TITLE
Could source for 1.6.1 (as indicated on Atmosphere) be pushed?

### ISSUE THREAD

**Issue by whileoneloop** [aldeed/meteor-tabular#327]
Hi Aldeed,

Have been enjoying tabular :)

Package version 1.5.5 in the current repo errors with a collection for 'tabular_records' already exists - as there are multiple calls to "new Mongo.Collection('tabular_records');".
## Version 1.6.1 seems to have less in tableRecords.js:

```
// We are creating a named client Collection that we will only modify from server
Tabular.tableRecords = new Mongo.Collection('tabular_records');

Tabular.getRecord = function(name) {
  return Tabular.tableRecords.findOne(name);
};
```

If there is a newer version of the package (e.g. 1.6.1 mentioned on Atmosphere 8th Apr) available than 1.5.5 could you please push?

Cheers,
Tim

**Comment by ghybs** [comment]
Hi,

It looks like the version 1.6.1 from Atmosphere could come from the repo [`devel`](https://github.com/aldeed/meteor-tabular/tree/devel) branch?
