### ISSUE TITLE
how to create action field "update, remove, other link" field?

### ISSUE THREAD

**Issue by yuomtheara** [aldeed/meteor-tabular#33]
I would like to create action field `update, remove, other link` for multi tabular table.
```js
// Tabular
{
     title: 'Action',
     tmpl: Meteor.isClient && Template.tabularAction
}

// Template
<template name="tabularAction">
    <div class="btn-group">
        <button type="button" class="btn btn-link dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <i class="fa fa-bars"></i>
        </button>
        <ul class="dropdown-menu dropdown-menu-right" role="menu">
            <li><a href="{{pathFor 'company.update}}" class="update">Update</a></li>
            <li><a href="{{pathFor 'company.remove'}}" class="remove">Remove</a></li>
        </ul>
    </div>
</template>
```
I don't want create the duplicate templates for multi tabular, so i want to pass any data from tabular table like router name, other value....
pl help me.

**Comment by aldeed** [comment]
The template is rendered with the row data as context. Can you get the info you need from there?

**Comment by yuomtheara** [comment]
Sorry i don't understand. so i must to create `tmpl: Meteor.isClient && Template.tabularAction` for one tabular table ???

**Comment by aldeed** [comment]
I'm saying if you use the same cell template in multiple tables, you can probably attach extra properties to the row context to be able to find out more about which table it is.

If it's only the collection reference that you need, then I guess there could be a TabularTable option that tells it to pass the collection in the cell template data context.

**Comment by yuomtheara** [comment]
how to attach extra properties to `tmp: Tabula...`?

**Comment by aldeed** [comment]
I may not be understanding what you're doing. Please provide a link to a reproduction or MeteorPad that shows what you are trying to do and what issue you are having.
