### ISSUE TITLE
How to sort/order with extraFields?

### ISSUE THREAD

**Issue by thearabbit** [aldeed/meteor-tabular#333]
I would like to `sort/order` with `extraFields`.

``` js
TabularTables.Books = new Tabular.Table({
  name: "Books",
  collection: Books,
  order: [[2, "desc"]],
  columns: [
    {data: "title", title: "Title"},
    {data: "author", title: "Author"}
  ],
 extraFields: ['otherField']
......
```

Please help me.

**Comment by aldeed** [comment]
Only columns can sort, but you could make it a column instead and set it to `visible: false`

**Comment by thearabbit** [comment]
Very thanks for your come back, miss you for along time.
Will c u on `AutoForm` too.
