### ISSUE TITLE
column().visible(false) does not work reliably on table within {{#if}} block.

### ISSUE THREAD

**Issue by soitech** [aldeed/meteor-tabular#335]
Like the title says. I went round and round trying to figure out why I could not reliably hide columns on my datatable, tried various methods, scoured the datatables api. 

In the end, I looked at what was different about that table from tables where the function worked fine, and tried pulling it out of the {{#if}} block in the template. Once I did that it now hides/shows columns appropriately. 

However, moving the table into another template, and putting that template in an {{#if}} block works fine. 

So:

```
{{#if hasPendingOrders}}
      <h4>Pending Orders</h4>
      {{> tabular table=TabularTables.PendingOrders class="table table-striped table-bordered"   id="pending-table"}}
{{/if}}
```

breaks column hiding functionality, but

```
{{#if hasPendingOrders}}
                {{>pendingOrderTable}}
{{/if}}
```

with

```
<template name="pendingOrderTable">
    <h4>Pending Orders</h4>
    {{> tabular table=TabularTables.PendingOrders class="table table-striped table-bordered" id="pending-table"}}
</template>
```

works fine. Easy enough to work around, but caused some time of confusion and frustration.

**Comment by aldeed** [comment]
This would be easier to fix if the exact code that calls `column().visible(false)` were posted.

**Comment by soitech** [comment]
That would help, wouldn't it.

```javascript
Template.pendingOrderTable.onRendered(function(){
  var pHide = [];

  if(Session.get('userSettings').hidePrices == true){
    pHide.push(3);
  }

    if(Roles.userIsInRole(Meteor.userId(),['practitioner'])) {
      pHide.push(2);
      pHide.push(5);
    }
  pHide.sort();
  $('#pending-table').DataTable().columns(pHide).visible(false);
});
```

If I recall I also rewrote this code multiple times while trying to get it to work, so what I ended up with was just what was working, not necessarily the best or most straightforward approach.

**Comment by aldeed** [comment]
I'm thinking this is something to do with the scoping of different Blaze templates and blocks. The timing of when onRendered fires versus evaluating `if`, etc. might cause the columns to not be ready yet. I'm not sure there is any solution other than to put it in its own template like you said.

**Comment by soitech** [comment]
That makes sense. Thanks. Easy enough to work around.
