### ISSUE TITLE
Session is not defined

### ISSUE THREAD

**Issue by knathanieltucker** [aldeed/meteor-tabular#337]
It seems that Session is not part of the default meteor bundle anymore, so when I installed tabular I got an error of session not defined. Simple fix and I added that in, but you should probably add it to your dependencies just in case it confuses some people.

**Comment by jonzacharuk** [comment]
Just confirming I had the same issue as above. Easy workaround with:

`meteor add session`

**Comment by aldeed** [comment]
Fixed in 2.0
