### ISSUE TITLE
Next page not working

### ISSUE THREAD

**Issue by chevelle123** [aldeed/meteor-tabular#338]
Hi,

Everything works perfectly on this except for the buttons that allow me to get to the next page. I'm using twbs bootstrap and downgraded my jquery to 2.2.4 due to a conflict. Any ideas why this isn't working?

**Comment by chevelle123** [comment]
When I inspect the button element on Chrome, I'm seeing href=# : 

![image](https://cloud.githubusercontent.com/assets/14037950/17889118/b15cfc0a-6926-11e6-84d9-186bd9390fe9.png)

**Comment by b-nugent** [comment]
Mine looks identical but it is working (I'm also using Bootstrap and the latest jQuery). The reason there is a # is that the html element is a link but not to another page. My suggestion would be to make another mini project with the latest version of jQuery and see if pagination is working in there.

**Comment by chevelle123** [comment]
Hi @b-nugent , what is your jQuery version? Mine is 2.2.4.

**Comment by b-nugent** [comment]
Actually I take it back, my jQuery is on 1.11.9 for this project, and my Bootstrap is on 3.3.6.

**Comment by chevelle123** [comment]
Thanks - how can I force my jQuery to be 1.11.9 for testing purposes? Thanks.

**Comment by b-nugent** [comment]
With Meteor, you should be able to type `meteor add jquery@version`, where "version" is the version number of the package you want to use.
