### ISSUE TITLE
Integrating the Editor Function

### ISSUE THREAD

**Issue by rhsu0268** [aldeed/meteor-tabular#342]
Hi, 

I am trying to implement the editor to my datatable. 

It doesn't seem to work. Someone from a previous post suggested doing:

Meteor.startup(function () {
    // insert here
    var editor = new $.fn.dataTable.Editor( {} );
});

But I am getting an error since meteor can't find '$'. Has anyone come across this and also what is the fix?

Thanks,
Richard

**Comment by aldeed** [comment]
Just need to import `$` and make sure your code is only on the client. Should work.
