### ISSUE TITLE
How to sort data on select field ?

### ISSUE THREAD

**Issue by ps0689** [aldeed/meteor-tabular#343]
Hello,
i want to sort data by date desc but the main issue is data time is my extra field.

`new Tabular.Table({
    name: "Brand table",
    collection: Brand,
    pageLength: 10,
    responsive: true,
    createdRow: function(row, data, dataIndex) {
        $("td:first", row).html(dataIndex + 1);
        return row;
    },
    columns: [{
        title: "Sno.",
        class: "col-sm-1"
    } {
        data: "name",
        title: "name",
        class: "col-sm-3"
    }],
    extraFields: ['showcase', "logo_image", 'created_date']
})`

**Comment by aldeed** [comment]
Make it a column with `visible: false` instead.
