### ISSUE TITLE
Responsive is hidding my custom template

### ISSUE THREAD

**Issue by luixal** [aldeed/meteor-tabular#346]
Hi,

I'm using a custom template for showing some action buttons on the last column of each row. The problem is when the screen is not enough big and the table goes into de responsive view.

I can see and click on the `+` button to expand the columns, but the column with the custom template is never shown.

Any ideas?

Thank!

**Comment by aldeed** [comment]
Can't say without a reproduction

**Comment by luixal** [comment]
It's hard to give a reproduction without including a (quite large) amount of code. If someone is facing this issue, I "solve" it avoiding DataTables to hide that column in responsive mode with responsivePriority, like this:

```javascript
columnDefs: [
  { responsivePriority: 0, targets: -1 }
]
```
