### ISSUE TITLE
Collection undefined error

### ISSUE THREAD

**Issue by vladblindu** [aldeed/meteor-tabular#35]
I have the following table which works ok. Beeing an admin account I published the whole Meteor.users collection. I also have two databases in a file in the root /lib

Clients = new Meteor.Collection("client");
Brands	= new Meteor.Collection("brand");

They are published for now like this in the /server/lib folder

Meteor.publish("pubClients", function(){
    return Clients.find();
});
Meteor.publish("pubBrands", function(){
    return Brands.find();
});
Meteor.publish("pubUsers", function(){
    return Meteor.users.find();
});

And subscribed like this in the client/lib folder

Meteor.subscribe('pubClients');
Meteor.subscribe('pubBrands');
Meteor.subscribe('pubUsers');

I am using the following template to inject the html:
{{> tabular table=TabularTables.Users selector=selector class="table table-striped table-bordered table-condensed"}}

Now if I try to change the Meteor.user to any of the Clients or Brands  collection or even inserting above this code a console.log(Clients) I get a: "Clients is not defined" error.
If I type in the console > Clients before running rerunning the app it works fine with Mongo.Collection etc.
If I run it I get the undefined message in the console too.
This is my  code ( in fact your code :) ):

TabularTables = {};

Meteor.isClient && Template.registerHelper('TabularTables', TabularTables);

TabularTables.Users = new Tabular.Table({
    name: "UserList",
    collection: Meteor.users,
    pub:"pubUsers"
    columns: [
	{data: "username", title: "User name"},
	{
	    data: "emails",
	    title: "Email",
	    render: function (val, type, doc) {
		return val[0].main
	    }
	},
	{
	    data: "emails",
	    title: "verified",
	    render: function (val, type, doc) {
	      return val[0].verified?"&#9745;":"&#9744;";
	    }
	},
	{
	    data: "profile",
	    title: "Account",
	    render: function (val, type, doc) {
	      return val.accType;
	    }
	},
	{
	    data: "profile",
	    title: "Active",
	    render: function (val, type, doc) {
	      return val.active?"active":"pending";
	    }
	},
	{
	    data: "createdAt",
	    title: "Singned up",
	    render: function (val, type, doc) {
		return moment(val).calendar();
	    }
	},
	{
	    tmpl: Meteor.isClient && Template.bookCheckOutCell
	}
    ]
});

I am using this collection in other points of the app and it works fine. Since I installed the tabular package
things got out of hand somehow. I don't have the slights idea were to start from.
I am struggling now for two days to get it working, but there's so few information on the web about this package (and most Meteor related subjects) that I decided to post this issue. 

Any ideas?

Thanks a lot.

**Comment by vladblindu** [comment]
ANSWERED! - on SO http://stackoverflow.com/questions/27875841/meteor-alddedtabular-collection-undefined-error/27876125#27876125
It's about load order. There's nothing wrong which the code, it's with the users!
Thanks anyway for all the goodies you are providing.

**Comment by aldeed** [comment]
Glad you figured it out. Note that by adding the `pub:"pubUsers"`, you're actually overriding a lot of the magic that makes this package work fast on large collections. If you'll never have many users, it might be fine.
