### ISSUE TITLE
changeSelector cannot use Session variables.

### ISSUE THREAD

**Issue by satyakvv** [aldeed/meteor-tabular#350]
I am trying to display data in tabular table which is dynamically published based on some criteria.
In the following sample, I would like username, fromDate, toDate to be taken from my Session variables or any client side variables.
TabularTables.Posts = new Tabular.Table({
  // other properties...
   changeSelector: function( selector, userId ) {
		selector.username = "Bob";
		selector.DOB = { $gte: fromDate, $lte: toDate };
		return selector;
	},
});

Issue: Session object is not defined in the chaneSelector function. Is there any other way to achieve this ?
Requirement: dynamic collection publication. The criteria is to be decided based on client-side variables

**Comment by aldeed** [comment]
You want to use the client side `selector`: https://github.com/aldeed/meteor-tabular#displaying-only-part-of-a-collections-data-set
