### ISSUE TITLE
Getting total number of rows (running count()) takes a long time

### ISSUE THREAD

**Issue by maxko87** [aldeed/meteor-tabular#351]
http://stackoverflow.com/questions/40272272/prevent-aldeed-meteor-tabular-from-showing-counts-at-the-bottom-of-tables

count()s in Mongo take a notoriously long time (even on indexed fields), and I have no need for the bottom of the table to show the exact count of matching items.

Is there any way to eliminate that number, or set tabular up such that the number is pulled in a different way?

**Comment by aldeed** [comment]
An option to turn off the total count might be nice. I'll accept a PR that adds this.

**Comment by maxko87** [comment]
@aldeed PR here: https://github.com/aldeed/meteor-tabular/pull/355/files

**Comment by aldeed** [comment]
I merged the PR and also added a skipCount option and documented both.
