### ISSUE TITLE
datatables.net-buttons is imported in main.js

### ISSUE THREAD

**Issue by derouck** [aldeed/meteor-tabular#353]
I tried to upgrade to the latest version but I noticed the buttons package is imported in the core package. As it's documented as a possible extension, the import should probably be removed from the core package.

https://github.com/aldeed/meteor-tabular/blob/43aeb3e0c7359879eca456d7d44d1de3a0cc0c03/client/main.js

If it's required you can probably make a small change in the readme about it. But I guess it slipped in the core because you're using that extension?

If you face an issue with this as well, you can easily work around it by doing the npm install for the buttons package.

Kind regards,

Chris

**Comment by aldeed** [comment]
Be sure you are using 2.0.2. This should have been fixed by that release.

**Comment by derouck** [comment]
Ok perfect, great update btw!!
