### ISSUE TITLE
ColVis button cannot use titleFn functionality

### ISSUE THREAD

**Issue by derouck** [aldeed/meteor-tabular#354]
If you use the buttons extension, it seems the ColVis button is unable to find the labels of the table when the title is set with titleFn.

Anybody facing the same issue? Or maybe there could be a workaround for this somehow by delaying ColVis or something like that.

**Comment by aldeed** [comment]
Yes, this would happen. I'll have to adjust the way titleFn works a little.

**Comment by thearabbit** [comment]
the same for me.
+1
