### ISSUE TITLE
Problem with 'columnVisibilityButton'!

### ISSUE THREAD

**Issue by thearabbit** [aldeed/meteor-tabular#356]
I tried to use `columnVisibilityButton`, It show but can't click (disable).
And It have problem when use with `titleFn` (don't show label title).

![2016-11-01_11-00-09](https://cloud.githubusercontent.com/assets/4495160/19879151/76d8ef0c-a022-11e6-85be-eafdb22831cd.png)

**Comment by aldeed** [comment]
titleFn issue is fixed. Not enough info to know what the other issue is.

**Comment by thearabbit** [comment]
I will try soon again.
