### ISSUE TITLE
how to access DataTables API in responsive config?

### ISSUE THREAD

**Issue by luixal** [aldeed/meteor-tabular#362]
Any idea about how to do something like this using tabular?

```javascript
responsive: {
  details: {
    renderer: $.fn.dataTable.Responsive.renderer.tableAll()
  }
}
```

More info here (DataTables docs): https://datatables.net/reference/option/responsive.details.renderer

Thanks!

**Comment by aldeed** [comment]
@luixal Does it not work? What specifically are the problems when you tried it?

**Comment by luixal** [comment]
Hmm... not sure right now, but I guess I couldn't acces the `tableAll()` function (which I'm supposing it's included in DataTables).

If you want me to, I can try it again (i finally went on a different approach).

**Comment by aldeed** [comment]
It is not included. You would need to `meteor npm install` the responsive extension packages.

https://datatables.net/download/npm#Extensions
https://github.com/aldeed/meteor-tabular#integrating-datatables-extensions
