### ISSUE TITLE
client side selector does not update table results

### ISSUE THREAD

**Issue by ayhid** [aldeed/meteor-tabular#363]
I have a client side selector using a reactive var and returned using a template helper

```javascript
Template.MyTemplate.helpers({
  selector(){
    return Template.instance().filters.get();
  }
});
```

I am also updating the so called selector value using an event

```javascript
Template.MyTemplate.events({
  'keyup input.js-search-filter': (event, template)=> {
    const currentTarget = $(event.currentTarget);
    const filters = template.filters.get();
    filters[currentTarget.data('filter-name')] = currentTarget.val();
    template.filters.set(filters);
  }
});
```
tabular template helper
`{{> tabular table=table selector=selector class="table table-striped table-bordered table-condensed"}}`
when typing some values into the input  the table does not update. Am I missing something here?

**Comment by aldeed** [comment]
I just tested client selector and it worked fine, but whatever your problem is, the code you posted doesn't show it. Make sure the helper is getting called and returning the value you expect.
