### ISSUE TITLE
How can I have a fontawesome icon as title to the table?

### ISSUE THREAD

**Issue by bharathkeshav12** [aldeed/meteor-tabular#369]
How do I set a fontawesome icon to the table header? in the tablular table declaration, i set `title: "columnTitle" `but am not able to replace it with any HTML tag.

**Comment by aldeed** [comment]
I'm guessing you can probably add a headerCallback and set the html of the title header element directly. See https://datatables.net/forums/discussion/22266/how-can-i-add-custom-html-attributes-to-the-header-column
