### ISSUE TITLE
Reusing the subscription mechanism to show the data as a Kanban board

### ISSUE THREAD

**Issue by lowi** [aldeed/meteor-tabular#370]
Hello @aldeed,

Your package is great and super-efficient!
I would like to reuse the subscription mechanism and present a Kanban board instead of dataTable.

It seems to me that I can reuse the whole part of the configuration + subscription, and instead of showing data as a table, show it in columns grouped by some configurable field.

Does it make sense? Should I try to extend your package and submit PR, or is it better to keep it separated?

**Comment by aldeed** [comment]
@lowi It is tempting to try to pull out the pub/sub aspects into a separate sharable package, but a lot of it is very specific to how the DataTables library defines options. It may or may not be possible, I haven't looked that closely, but if you manage to do it well, I'd be willing to change this package to depend on a separate shared data handling package.

**Comment by lowi** [comment]
@aldeed Thanks for the answer. Depending on the time I have, I'll get back to you with a package that would abstract it.
