### ISSUE TITLE
Collections helper parameters

### ISSUE THREAD

**Issue by jdnichollsc** [aldeed/meteor-tabular#371]
Hi guys,

It's possible to send parameters using helpers?

For example:

```
columns: [
  {data: "type(productTypeCode)", title: "Full Name"},
]
```

and from collection helpers:
```
AppFeedback.helpers({
  type(productTypeCode) {
    var type = Types.findOne({ code: productTypeCode });
    return type && type.value;
  }
});
```

Thanks in advance, Nicholls

**Comment by aldeed** [comment]
@jdnichollsc, that isn't possible, but if `productTypeCode` is on the AppFeedback document, then `this.productTypeCode` should work in your helper function.
