### ISSUE TITLE
How to set default page length?

### ISSUE THREAD

**Issue by VansonLeung** [aldeed/meteor-tabular#372]
The table is always of 10 items per page.
I want it to be more by default.
How to set it?
Thanks

**Comment by aldeed** [comment]
This package wraps the DataTables package, and the answer can be found in their documentation: https://datatables.net/reference/option/pageLength

**Comment by VansonLeung** [comment]
Thanks, after testing, it is as simple as:

new Tabular.Table({
...
      pageLength: 50,
...
    });


new Tabular.Table({
...
      pageLength: -1,
...
    });
