### ISSUE TITLE
Could I use tabular with "Ms SQL"?

### ISSUE THREAD

**Issue by thearabbit** [aldeed/meteor-tabular#377]
I plan to use `Ms SQL` by `node-mssql` of npm.
Could I use tabular with "Ms SQL"?
Pl help me.

**Comment by jdnichollsc** [comment]
This plugin only works with Mongo, because is reactive...

**Comment by thearabbit** [comment]
Thanks for your reply, have any package on node for this?

**Comment by aldeed** [comment]
If not using Mongo/DDP subscriptions, you really can just use the DataTables package directly with an `ajax` callback: https://datatables.net/reference/option/ajax
