### ISSUE TITLE
don't auto update when insert new doc?

### ISSUE THREAD

**Issue by yuomtheara** [aldeed/meteor-tabular#38]
I used two browser, one to view tabular data and one to insert data.
but when i insert new data, the tabular don't auto update (for update and remove action is ok).

**Comment by aldeed** [comment]
1.0 is released and should fix this. Please see updated [README](https://github.com/aldeed/meteor-tabular/blob/master/README.md) for all features and options.

**Comment by yuomtheara** [comment]
thanks, for your helping.
