### ISSUE TITLE
dataTables responsiveness is not working

### ISSUE THREAD

**Issue by FranciscoHanna** [aldeed/meteor-tabular#381]
I am facing this problem on Meteor 1.4.2.3 and latest version of aldeed:tabular
Tables on mobile do not collapse.

Adding the following options do not solve the problem:

responsive: true,
autoWitdh: false

The solution provided in #201 does not work for me.

**Comment by FranciscoHanna** [comment]
Solved! I forgot to add the DataTables Responsive extension using NPM. Then I added this on client side code:

```javascript
import { $ } from 'meteor/jquery';
import dataTablesBootstrap from 'datatables.net-bs';
import 'datatables.net-bs/css/dataTables.bootstrap.css';
import dataTableResponsive from 'datatables.net-responsive';

dataTablesBootstrap(window, $);
dataTableResponsive(window, $);
```

**Comment by rafinskipg** [comment]
@FranciscoHanna  did you had to do anything more?

**Comment by FranciscoHanna** [comment]
@rafinskipg Nope. That was all!

**Comment by defionscode** [comment]
@FranciscoHanna you should prob close this issue then if it's no longer a problem

**Comment by FranciscoHanna** [comment]
@defionscode  I forgot, sorry. There it is.
