### ISSUE TITLE
Exception while invoking method 'tabular_getInfo' Error: Did not check() all arguments during call to 'tabular_getInfo'

### ISSUE THREAD

**Issue by etamity** [aldeed/meteor-tabular#39]
I20150116-16:32:36.177(0)? Exception while invoking method 'tabular_getInfo' Error: Did not check() all arguments during call to 'tabular_getInfo'
I20150116-16:32:36.179(0)?     at [object Object]._.extend.throwUnlessAllArgumentsHaveBeenChecked (packages/check/match.js:357:1)
I20150116-16:32:36.179(0)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:112:1)
I20150116-16:32:36.179(0)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1596:1)
I20150116-16:32:36.179(0)?     at packages/ddp/livedata_server.js:648:1
I20150116-16:32:36.179(0)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150116-16:32:36.180(0)?     at packages/ddp/livedata_server.js:647:1
I20150116-16:32:36.180(0)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150116-16:32:36.180(0)?     at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
I20150116-16:32:36.180(0)?     at packages/ddp/livedata_server.js:546:1

Hi there,
I am following the example, butI am getting this error, is there any way to fix?
By the way, how can I pass dynamic column array?
	TabularTables = {};

	TabularTables.Users = new Tabular.Table({
		 name: "Users",
		collection: this.collection,
		columns: function (){
				var result= [];
				_.map(this.fields,function(field){

					var item = {data:field.name,title:field.name};
					result.push(item);
				});

				return result;
			}
	});

It seems doesn't work.

**Comment by aldeed** [comment]
1.0 is released and should fix this. Please see updated [README](https://github.com/aldeed/meteor-tabular/blob/master/README.md) for all features and options.
