### ISSUE TITLE
After changing "Show xxx entries" and clicking next page in the pagination, the "Show xxx entries" resets to the default value. 

### ISSUE THREAD

**Issue by jasonxeno** [aldeed/meteor-tabular#40]
Congrats on 1.0!!! Thank you so much, I'm very excited.

Very minor issue probably:
After changing "Show xxx entries" and clicking next page in the pagination, the "Show xxx entries" resets to the default value.

Just to check to make sure it wasn't my app I made a bare bones repo:
https://github.com/jasonxeno/tabular-issue

Change amount of entries to 100.
Go down and click next to view next page.
Entries resets to 10 and only 10 results appear.

**Comment by aldeed** [comment]
I think I noticed that during development and forgot to look into it. Will investigate.

**Comment by aldeed** [comment]
Fixed in v1.0.1

**Comment by jasonxeno** [comment]
Thank you!
