### ISSUE TITLE
Any ideas or clues on why the column size responsiveness of table columns would change between 0.2.3 and 1.0.0?

### ISSUE THREAD

**Issue by jasonxeno** [aldeed/meteor-tabular#41]
Any ideas or clues on why the column size responsiveness of table columns would change between 0.2.3 and 1.0.0?

It looks like with 1.0.0 the columns are trying to be equal sizes now in my app.

Only thing that has changed is the tabular package version in these two screenshots:

0.2.3: date not squished, and columns take up room depending on what they need:
![tabular023](https://cloud.githubusercontent.com/assets/6493925/5790809/9a5f478e-9e6f-11e4-800b-1eb4d4f41f98.png)

1.0.0 date is squished, and columns are taking up more room than they need
![tablular100](https://cloud.githubusercontent.com/assets/6493925/5790808/9913f0dc-9e6f-11e4-82f1-ba55fcda604a.png)

Thank you for any insight on the matter.

**Comment by aldeed** [comment]
Not sure. They both use the same version of DataTables library, so it might be related to how it's generating the options that are passed to the DataTable.

**Comment by jasonxeno** [comment]
Your hunch is true, it's related to how the options are generated. If I set the option "autoWidth: false" then the columns are as they were in 0.2.3.

In the DataTables docs:
https://datatables.net/reference/option/autoWidth

It says that autoWidth is supposed to default to true, and that somehow wasn't happening in 0.2.3. Since you didn't do anything with autoWidth, I'm guessing that it was a bug in DataTables itself where defaults were not being set under certain circumstances.

Regardless, DataTables indeed works as intended with options in 1.0.0. :)

**Comment by aldeed** [comment]
Just tested this and came to the same conclusion. :)

**Comment by ababra** [comment]
+1 @jasonxeno Setting autoWidth: false fixes the column-width issue. Could this be potentially hard-coded into a future release, to override the Datatables library functionality? If not, can it get a mention in the documentation?

**Comment by aldeed** [comment]
@ababra updated readme in https://github.com/aldeed/meteor-tabular/commit/111958f9b418649a5e7eb7042413a6f82e7b8060
