### ISSUE TITLE
Event map support on tables?

### ISSUE THREAD

**Issue by blargity** [aldeed/meteor-tabular#42]
Hi there,

This package is awesome. Just found it a few days ago and I've been playing around to see if it'll do everything I need it to.

The only issue I've hit is I can't seem to detect clicks on table rows. Here's the table definition:

```javascript
TabularTables.Users = new Tabular.Table({
    name: "UserList",
    collection: Meteor.users,
    columns: [
        {data: "username", title: "Username"},
        {data: "emails[0].address", title: "Email"},
        {data: "profile.name", title: "Name"}
    ]
});
```

Here's the Template:

```html
<template name="Users">
    {{> tabular table=TabularTables.Users class="table table-striped table-bordered table-condensed"}}
</template>
```

Then I have this JS to try to detect row clicks:

```javascript
if (Meteor.isClient) {
    Template.Users.events({
        'click tr': function(event) {
            alert(event.currentTarget);
        }
    });
}
```

But it doesn't seem to get fired. How should I be checking for row clicks? Is this being overridden by DataTables somehow?

**Comment by jasonxeno** [comment]
If you make your columns into templates with the tmpl feature, you can control all the events and grab the row object when any part of the row is clicked.

Is there a faster method without making templates for each column if you want to make the whole row click an event and grab the object context?

With the reactive-tables package you can click anywhere in the row and get the data context.

```javascript
Make the event selector be tr, and you'll have your row object in this:

Template.posts.events({
  'click .reactive-table tr': function (event) {
    // set the blog post we'll display details and news for
    var post = this;
    Session.set('post', post);
  }
});
```

I tried reading into the reactive-tables code to find a method to do this with tabular, but I couldn't quite understand how it was allowing the context to get grabbed on click.

Is the clicked row object stored within the DataTables context perhaps? I tried looking in the DataTables object but couldn't find the actual current row data.

Meanwhile, the tmpl method for columns will work though for grabbing the row object.

**Comment by aldeed** [comment]
I just tried with v1.0.1 and it's working for me:

```js
Template.myTemplate.events({
    'click tr': function (event) {
      var data = $(event.target).closest('table').DataTable().row(event.currentTarget).data();
    }
});
```

**Comment by jasonxeno** [comment]
Ah I see, that works perfectly. That code gets the object in the clicked row for me also.

My problem was that I was thinking Meteor would somehow put the object at that row in the 'this' context of the event.

But grabbing it from the event and DataTables api like you showed above works great!
