### ISSUE TITLE
Conditional formatting

### ISSUE THREAD

**Issue by kirilan** [aldeed/meteor-tabular#43]
Hi,
I am fairly new to meteor and this wonderful packet but. I am having trouble figuring out how I would be able to format a specific row on a condition. For example if a data field has certain value I would like to be able to set some style class to that particular row to make the text highlight as red "warning\error". 

I am assuming this is somehow doable using the DataTables API but I was unable to figure out how it's done.

Thanks in advance.

my code looks something like this 

```js
Template.CreqSystemsView.rendered = function() {
  var self = this;
  table = self.$('CREQ').dataTable({
    fnRowCallback: function(nRow, aData, iDisplayIndex, iDisplayIndexFull) {
      if ($(nRow).find('td:eq(5)').text()=='N') {
        $(nRow).find('td:eq(5)').addClass('color');
      }
    }
  });
};
```

**Comment by aldeed** [comment]
Try using the [createdRow](http://datatables.net/reference/option/createdRow) callback, and put it in with the rest of your options in the Tabular.Table constructor:

```js
TabularTables.Books = new Tabular.Table({
  // other properties...
  createdRow: function( row, data, dataIndex ) {
    // set row class
  }
});
```

**Comment by kirilan** [comment]
thank you that works like a charm :) might be worth adding available callbacks in the readme too :)

**Comment by aldeed** [comment]
I am not affiliated with DataTables and it's a giant library so I'd rather not document anything related to it. The readme only documents tabular wrapper around DataTables.

**Comment by saidani91** [comment]
hi, 
I tried :
TabularTables.myTable= new Tabular.Table({
 ...
createdRow: function( row, data, dataIndex ) {
 if (data[4] < 0)
               $('td', row).addClass('danger');
  }
});
that's not working and by inspecting the elemnt its adding a strange class "sorting_1" ! 
i tried instead  $('td', row).css('color':'red');
it works but coloring the whole line and all i want is the specific cell
