### ISSUE TITLE
v1.0.1 => processing.dt stopps firing

### ISSUE THREAD

**Issue by boustanihani** [aldeed/meteor-tabular#44]
After upgrading to v1.0.1 the processing event (**processing.dt**) stopped firing.
Check: https://datatables.net/reference/event/processing

I was using this code below to show a custom spinner when data is being processed:
```javascript
$(window).on('processing.dt', function(e, settings, proc) {
    vars.set('processing', proc); // Reactive...
});
```

**Comment by aldeed** [comment]
Copying and pasting your event handler into v1.0.3, it fires for me. If it still isn't working for you, provide a reproduction app or MeteorPad.

**Comment by boustanihani** [comment]
When will v1.0.3 be published ?

**Comment by boustanihani** [comment]
Never mind, I was confused by the github release verion, I will test this again...
