### ISSUE TITLE
v1.0.1 => pagination index not being reset!

### ISSUE THREAD

**Issue by boustanihani** [aldeed/meteor-tabular#45]
After upgrade to v1.0.1 the **pagination index is not being reset**, I mean if I am looking at apples and switch to page 2 and then decide to display oranges I will also be looking at page 2.

The pagination index should be reset when **another table** is displayed.

**Comment by aldeed** [comment]
I believe this should be fixed now in 1.0.3. If not, please provide a more detailed reproduction or MeteorPad example.

**Comment by kirilan** [comment]
I was able to reproduce this item I guess I will raise a new issue as this is closed.
