### ISSUE TITLE
get some data with Collection.find()?

### ISSUE THREAD

**Issue by yuomtheara** [aldeed/meteor-tabular#49]
I would like to get some data like:
```
....
  name: "BookList",
  collection: Books.find(...),
  columns: [
....
```

**Comment by kirilan** [comment]
from the readme:

TabularTables.AppFeedback = new Tabular.Table({
  name: "AppFeedback",
  collection: AppFeedback,
  pub: "tabular_AppFeedback",
 // other options
});

**Comment by aldeed** [comment]
This is what the `selector` attribute is for. See the readme.
