### ISSUE TITLE
Make fully reactive

### ISSUE THREAD

**Issue by mrsolo5k** [aldeed/meteor-tabular#5]
Hi @aldeed!

I'm struggling with this issue a while now. I'm quite new to meteor, so maybe I misunderstood something. When I update some entry in DB, datable re-renders fine, but when I insert new entry to collection nothing is happening on client side until I perform manual action to trigger re-render of datatable.

I also used custom publish function to return whole collection (not specific ids), but encountered the same issue. I even downloaded your repo and tried to fix this, but with no luck so far. That's why I decided to ask for your advice.

I really need this to work soon for one simple commercial app, which I've recently updated to Meteor 1.0+ and that's why I searched for compatible datatables library and came across your's sollution. Before update I was using https://github.com/LumaPictures/meteor-jquery-datatables and it worked fine, but now it's not compatible with the newest version of Meteor.

Thanks!

**Comment by spikey82** [comment]
Hi,

I also use your component, which is great. I was also struggling with the reactivity, but I use the following jquery 'hack' ;) to manual trigger the update (client-side):

```javascript
$('select').val($('select').val()).change();
```
What is does that it manually triggers a change event on the select box. The new value is the same as the old value so it forces the table to redraw, but it keeps the pagination state intact...

**Comment by aldeed** [comment]
1.0 is released and should fix this. Please see updated [README](https://github.com/aldeed/meteor-tabular/blob/master/README.md) for all features and options.

**Comment by alexpyslar** [comment]
Hi @aldeed,
I use meteor 1.8 and latest tabular.
When doc is added to collection table gets updated properly, but in case of removal nothing happens till page refresh.
Does logic handle removal with reactivity or just addition?
