### ISSUE TITLE
v1.0.4 => pagination index not being reset!

### ISSUE THREAD

**Issue by kirilan** [aldeed/meteor-tabular#50]
similar to : https://github.com/aldeed/meteor-tabular/issues/45

when viewing a table let's say you are on page 4 (Showing 31 to 40 of 51 entries) and clicking on a row triggers an event that changes the "selector" so your table no longer has 51 elements but  < 10 and the pages navigation is now 1 page. the cursor stays at page 4 (Showing 31 to 4 of 4 entries) and the Table is sitting at "No matching records found" . if you then click manually on page 1 you see the intended view. 

I am guessing that there are 2 possible ways to go around this. either auto select page 1 when the result set only has 1 page or reset page index when selector is changed. I think the latter may be more appropriate.

**Comment by kk4sh** [comment]
In my own implementation i cannot reproduce the described behavior. 
As soon as the selector has being called than the table goes to page 1.

**Comment by boustanihani** [comment]
This has been fixed, see => https://github.com/aldeed/meteor-tabular/issues/45

**Comment by kk4sh** [comment]
As a surrounding matter, is there a way to avoid this behavior?
I want to use the dt to navigate through the items by selecting a row. 
But, each click on an item triggers an event and make the table comes to the first page even if the selector has not changer. 
Any tips are welcome 
Thanks.

**Comment by aldeed** [comment]
@kk4sh please create a reproduction of your issue in a repo or with MeteorPad and file it as a new issue. It should be fixable if I have a reproduction to work from. Thanks.
