### ISSUE TITLE
How to display filtered records?

### ISSUE THREAD

**Issue by rajpant** [aldeed/meteor-tabular#51]
Hi There,

I have a collection which contains 1000 records, i have a flag status(true/false) in the collection.

I need to display only the records which are having status flag true.
in sort:
Total records : 1000
active status: 700
inactive status : 300

How can I display only active records? It shows 1-50 of 1000. Could you please help me out..

**Comment by kirilan** [comment]
create a subscription that only includes your desired state records and reference the subscription in the table definition. 
It's described in the examples from the readme.

**Comment by rajpant** [comment]
Hi Kirilan,

Thank you for your Reply.

**Comment by aldeed** [comment]
There's no need to create a subscription. Just include a `selector` attribute on the table, as described in the readme.
