### ISSUE TITLE
Is possible to translate columns title?

### ISSUE THREAD

**Issue by ixdi** [aldeed/meteor-tabular#53]
Is there a way to translate title strings from table headers ?

I'm using tap-i18n, I have also tried to call a function like:

```js
tap = function (str) {
    return (Meteor.isClient) ? TAPi18n.__(str)  : " ";
}
... and then use
{ data: "someField", title: tap('name') }
  
```
but nothing is translated, it returns "name".

Thanks

**Comment by kirilan** [comment]
maybe try using the "render" callback as the example from the readme: see below

bularTables.Books = new Tabular.Table({
  name: "BookList",
  collection: Books,
  columns: [
    {data: "title", title: "Title"},
    {data: "author", title: "Author"},
    {data: "copies", title: "Copies Available"},
    {
      data: "lastCheckedOut",
      title: "Last Checkout",
      render: function (val, type, doc) {
        if (val instanceof Date) {
          return moment(val).calendar();
        } else {
          return "Never";
        }
      }
    },
    {data: "summary", title: "Summary"},
    {
      tmpl: Meteor.isClient && Template.bookCheckOutCell
    }
  ]
});

**Comment by ixdi** [comment]
It's ok if using

```js
Template.<name>.rendered = function () {
     _.each($('thead tr th'), function (o) {
           $(o).html(TAPi18n.__($(o).html()));
     });
}
```
and setting title of each column as the string you have defined inside i18n.

I haven't found a direct method, without the need to use Template rendered callback.

**Comment by aldeed** [comment]
I'm not sure of the answer, but tabular does nothing special here, so it's best to look for the answer in the [DataTables documentation](http://datatables.net/reference/option/columns.title). Looking at your original code, I think it would work. The `isClient` check is unnecessary because the server never attempts to execute any of the column stuff.

**Comment by domq** [comment]
See http://stackoverflow.com/questions/35647656/how-do-i-get-translated-column-headers-with-meteor-and-aldeedtabular/35650141#35650141 for a solution using the `.template.options` reactive variable.

**Comment by diegonc** [comment]
Hi @domq, I'm looking at the solution you proposed and I think it only work with one table, right?

I beleive the following approach could work
```
if (Meteor.isClient) {
  Template.tabular.onRendered(function() {
    if (this.tabular.tableName.get() !== 'Books') return;
    var self = this;
    self.autorun(function() {
      var options = _.clone(self.tabular.options.get());
      options.columns = getTranslatedColumns();
      self.tabular.options.set(_.clone(options));
    });
  });
}
```
where `if (this.tabular.tableName.get() !== 'Books') return;` was added to the listener.

There will be one listener per table! I guess it could be done more efficiently somehow (a global registry of columns generator functions comes to mind), but for a few tables it's acceptable :)

**Comment by dwimberger** [comment]
Recent versions of aldeed:tabular / datatables allow to specify a function for setting the column titles.

    import {TAPi18n} from 'meteor/tap:i18n';

    TabularTables = {};
    TabularTables.Departments= new Tabular.Table({
      name: 'Departments',
      collection: Departments,
     responsive: true,
     autoWidth: true,
     stateSave: false,
     columns: [
        {data: "name", titleFn: function() {
          return TAPi18n.__("name");
        }},
        {data: "description", titleFn: function() {
          return TAPi18n.__("description");
        }}
      ]
    });

The language change is reactive. If you have translations you can switch and columns will be translated.

    TAPi18n.setLanguage("en");
    TAPi18n.setLanguage("de");

Word of warning: 
This currently does not work when you include invisible columns in your table data. The offset is wrong and you get wrong column titles.

**Comment by MohammedEssehemy** [comment]
@dwimberger @aldeed 

> Word of warning:
This currently does not work when you include invisible columns in your table data. The offset is wrong and you get wrong column titles.

I'm still experiencing this same issue.

**Comment by MohammedEssehemy** [comment]
@ixdi Thanks, your solution works fine.
