### ISSUE TITLE
question: using DataTAbles plugin ?

### ISSUE THREAD

**Issue by kirilan** [aldeed/meteor-tabular#54]
is it possible to use DT plugins and if yes can someone please help me understand how I would add one such as this:
http://jquery-datatables-column-filter.googlecode.com/svn/trunk/index.html

**Comment by aldeed** [comment]
In general, any plugin that works with DataTables 1.10+ should work. However, tabular may need some additional logic to support column filtering. I haven't tested it.

```js
Template.myTemplate.rendered = function () {
  this.$('table').DataTable().columnFilter();
};
```

**Comment by kirilan** [comment]
I am not able to make it work
does the source file need to be in a specific location or referred to somehow.

http://jquery-datatables-column-filter.googlecode.com/svn/trunk/media/js/jquery.dataTables.columnFilter.js

**Comment by bySabi** [comment]
You can put plugins files on `client/compatibility` folder.
