### ISSUE TITLE
Get the collection used by table

### ISSUE THREAD

**Issue by justindra** [aldeed/meteor-tabular#60]
Hi,

Is it possible to get the collection used by the table? Say I want to add an update function in the table itself.

Cheers,

Justin

**Comment by aldeed** [comment]
You might be able to do `Template.instance().tabular.collection`, but it depends on exactly how your code is structured.

It's possible that a better way could be added.

**Comment by aldeed** [comment]
In the next release you will be able to do `Tabular.tablesByName.yourTableName.collection`
