### ISSUE TITLE
Custom tabular table rendered

### ISSUE THREAD

**Issue by Errbel** [aldeed/meteor-tabular#63]
Hi,

Is there a way to specify what elements should be rendered by tabular ?

For example to hide/remove the filter bar, something like:

{{> tabular table=TabularTables.Users class="table table-striped table-hover" **data-search='false'**}}

Want to specify it to hide/remove pagination, table header...

Thx

**Comment by aldeed** [comment]
Your question is about DataTables, not tabular. See [the dom option](http://datatables.net/reference/option/dom).
