### ISSUE TITLE
conflict with houston:admin package

### ISSUE THREAD

**Issue by dkoo761** [aldeed/meteor-tabular#65]
For some reason, after installing the houston:admin package, the following statement returns false:

```Meteor.users instanceof Mongo.Collection```

As a result, meteor-tabular doesn't recognize Meteor.users as a collection and I get a server-side error to that effect when trying to define a table. This should probably be fixed in Houston but thought I would mention it here in case (1) a workaround can be provided in meteor-tabular or (2) someone else runs into the same problem as it took me a couple hours to debug today.

**Comment by aldeed** [comment]
I see this issue come up a lot in various places. I don't know why they haven't fixed it yet. I'd rather not do workarounds for issues caused by other packages, but thanks for posting.

**Comment by dkoo761** [comment]
Agreed, it's not your problem.
