### ISSUE TITLE
Case-insensitive column sorting

### ISSUE THREAD

**Issue by dkoo761** [aldeed/meteor-tabular#66]
It appears that the default column sorting is case-sensitive. Is there a way to override this without creating a custom publication? I think case-insensitive would be a better default as I can't think of scenario where I would prefer case-sensitive sorting.

I looked at the docs for DataTables as they provide a lot of sorting plugins but they are only client-side and I'm pretty sure sorting is done server-side in the tabular package.

**Comment by aldeed** [comment]
It's using normal MongoDB sorting on the server. Is that case-sensitive?

**Comment by dkoo761** [comment]
Apparently not, I discovered this JIRA shortly after posting this issue: https://jira.mongodb.org/browse/SERVER-90

It seems like having a lowercase version of all sortable document properties is the current official solution. Well I just learned something new about Mongo.

**Comment by aldeed** [comment]
That's unfortunate. I don't think there can be a workaround since the goal of this package is to have just-in-time publication with paging for large datasets. This requires allowing mongo to do the sorting.

**Comment by dkoo761** [comment]
That's fine, I'm going to normalize sortable data where possible before writing it to the DB (for example, titleize "firstname" to "Firstname"). Where normalizing isn't possible and sorting is needed, I'll just create a lowercase copy of the field in the DB and sort on that.
