### ISSUE TITLE
Security issue - modifying selector client-side allows user to see all data in collection

### ISSUE THREAD

**Issue by dkoo761** [aldeed/meteor-tabular#67]
After the page loaded, I changed the selector function from my browser console to the following:

```javascript
Template.users.helpers({
    selector: function () {
        return {}
    }
})
```

I then navigated to a different page in my app and then came back to the page with the table (to trigger the template to reload).

The table now shows all of the users in the collection instead of the the ones specified in the original selector. So it appears that the template selector doesn't provide any real security in preventing a user from seeing the contents of the collection. Is there another way to accomplish securing the collection from this type of "selector attack"? Would a custom publication do the trick?

**Comment by aldeed** [comment]
So far the security I've added can prevent publishing entirely based on user and/or can prevent publishing some fields.

It sounds like your goal is to allow the table to show only certain documents, maybe like limiting to documents where `owner` property is the current user. This isn't yet supported but could be. Probably the simplest way would be to have a "base selector" as part of the table definition, which would be added to the client-provided selector in the publish function on the server. It could optionally be set to a function that takes the userId and returns the base selector.

**Comment by aldeed** [comment]
And, yes, you could currently mitigate by using a custom publish function that merges ID list and your base selector into a single selector with AND relationship.

**Comment by dkoo761** [comment]
Your solution of merging a base selector + template selector is exactly what I was thinking. In fact, I actually added a selector property to my Tabular.Table definition by accident before I realized that it was supposed to be added as a template helper. If you think this is something you'll add in the next week or two then I'll hold off on using a custom publish function for now. I'd be happy to have a go and submit a PR for the base selector feature if you'd like.

**Comment by aldeed** [comment]
PR would be great. Otherwise I think I'll get to it within a week or so.

**Comment by dkoo761** [comment]
OK, I'll try and submit the PR tomorrow.

**Comment by dkoo761** [comment]
Thanks @hockeyj85, I was just about to work on this and see you've already done it!

@aldeed We're launching a project next week that requires this PR. Any chance you'd be able to merge it & version bump by Monday? Pretty please? :)

**Comment by aldeed** [comment]
Merged and released.

**Comment by dkoo761** [comment]
You're the best!!!

**Comment by dkoo761** [comment]
I think the readme might be slightly off as it says "Selectors provided this way will be merged with selectors provided to the template overwriting them if there are any conflicts." But actually you're using $and rather than overwriting either selector.

**Comment by aldeed** [comment]
@dkoo761, good catch. The PR was overwriting, but I switched it to use $and. Forgot to update the docs, so I'll do that now.
