### ISSUE TITLE
Tabular.Table scope ?

### ISSUE THREAD

**Issue by Errbel** [aldeed/meteor-tabular#68]
Hi,

If I declare a **Tabular.Table** in an **other directory** I got :
          
            ReferenceError: Books is not defined    
             at app/lib/table.js:23:15

File structure exemple:

               client/
               server/
               collection/BooksCollection.js
               lib/table.js
              ==> ERROR

               client/
               server/
               collection/BooksCollection.js
               collection/table.js
              ==> NO ERROR

               client/
               server/
               collection/BooksCollection.js
               table.js
              ==> NO ERROR

Something wrong ?

**Comment by kirilan** [comment]
I think your table definition is executed before your collection is instantiated in memory therefore fails. you probably need to place your collection definition in lib so it gets processed before the tables

**Comment by aldeed** [comment]
Agree. This is just a typical load order issue, not related to tabular pkg.

**Comment by Errbel** [comment]
Ok, thx for your explanation guys !

**Comment by Achtel** [comment]
Hi guys, I'm getting the same error but both my table definition (documentTable.js) and its associated collection (images_documents.js) are in the same location:

|-collections
|--documentTable.js
|--images_documents.js

It may be worth noting that the Documents collection is a FS.Collection... 

`  Documents = new FS.Collection("Documents", {
    stores: [docStore],
    filter: {
      allow: {
        contentTypes: ['application/pdf']
      }
    }
  });`

Would this affect anything?
