### ISSUE TITLE
Using Meteor.users as collection drops error 'options must specify collection'

### ISSUE THREAD

**Issue by ddresch** [aldeed/meteor-tabular#74]
If I try this simple table definition the `instanceof Mongo.Collection`check in `tabular/common.js` fails:

    TabularTables.Users = new Tabular.Table({
      name: "UsersList",
      collection: Meteor.users,
      columns: [
        {data: "username", title: "Username"}   
      ]
    });

Maybe it's corresponding to this issue: https://github.com/matb33/meteor-collection-hooks/issues/34

I'm not using `meteor-collection-hooks` directly I guess it's used by `collection2` package, right?

Any hint how to get around this issue?

**Comment by aldeed** [comment]
collection2 does not use collection-hooks, but this same issue has been happening a lot recently when houston pkg is used. I haven't dug into it.

**Comment by ddresch** [comment]
So tracked it down to this package `dburles:mongo-collection-instances` which is causing the effect. It is also used by the `houston` package you mention. 

For a quick check you can use this repo: https://github.com/ddresch/meteor-tabular-meteor-users

Remove or add the package and you'll see it directly after server restart.
