### ISSUE TITLE
1. You're awesome. 2. Is there a demo app somewhere?

### ISSUE THREAD

**Issue by elie222** [aldeed/meteor-tabular#75]
1. You're awesome. Simple-schema, collection2, autoform and now this? Great work

2. My actual question, is there a demo app up yet?

**Comment by aldeed** [comment]
1. :blush:
2. No. I have one I've been using for testing, but I need to improve it a bit before posting.

**Comment by theduke** [comment]
+1 for being awesome.

**Comment by kirilan** [comment]
+1

**Comment by dkoo761** [comment]
+1 indeed!

**Comment by hanchang** [comment]
:+1: here too, really good stuff, just wanted to make sure you know you're appreciated :)

**Comment by aldeed** [comment]
Thanks all. :grinning:

**Comment by brylie** [comment]
Hi all. I created a basic [demo app on Meteorpad](http://meteorpad.com/pad/xNafF9N5XJNrFJEyG/TabularDemo).

**Comment by AnnotatedJS** [comment]
Hi Y'all,

Have a look at http://greatalbums.meteor.com/albums for a working demonstration of a Collection with reactively CRUD using aldeed:tabular, aldeed:autoform

The source is on github, https://github.com/AnnotatedJS/GreatAlbums

You can signin with email "admin@demo.com" and password "password".

René
AnnotatedJS

**Comment by aldeed** [comment]
Thanks @AnnotatedJS!
