### ISSUE TITLE
How to integrate Extensions like TableTools?

### ISSUE THREAD

**Issue by hanchang** [aldeed/meteor-tabular#82]
Is Tabular compatible with DataTables extensions like TableTools?
If so, do you have any tips on how to integrate TableTools with Tabular?

**Comment by ababra** [comment]
Have yet to try TableTools, but can confirm ColVis and ColReorder work just fine with this package. Go to the official site (https://datatables.net/download/index), download the respective JS and CSS for your extension and drop them in your "client" folder in your Meteor project. Use the "dom" property to enable the extension:

lib/collections.js
````
// DataTables initialization
TabularTables = {};
Meteor.isClient && Template.registerHelper('TabularTables', TabularTables);

// Orders
Orders = new Mongo.Collection("orders");
TabularTables.Orders = new Tabular.Table({
  name: "Orders",
  collection: Orders,
  // This is the important part, read the documentation on the official site for more info
  dom: 'C<"clear">lRfrtip',
  columns: [
	{ data: 'order_id', title: 'Order #' },
	{ data: 'order_price', title: 'Price' },
	{ data: 'order_notes', title: 'Notes', visible: false }
  ]
});
````

**Comment by hanchang** [comment]
Hm, good to know - the issue with TableTools is that there's a .swf file that also needs to be loaded which I'm having trouble with.

**Comment by ababra** [comment]
Put the SWF file in the following folder:

<app>/Public/swf/copy_csv_xls_pdf.swf

Looks like TableTools is hard-coded to look for a "swf" subfolder.

**Comment by kirilan** [comment]
Guys if this works I am going to find a way to buy you beers.
K

-----Original Message-----

**Comment by aldeed** [comment]
I have succeeded in getting csv/xls working with a Meteor app before, so I can find the correct code if you can't figure it out. It wouldn't be a bad idea to document it in this pkg readme.

**Comment by hanchang** [comment]
Awesome, thanks @ababra, that was the tip I needed, should have dived into the TableTools source instead of the Tabular source, that was less than intelligent of me.

I just created PR #97 with the information I learned from this process in hopes of saving the next person some time and headache trying to figure it out!

**Comment by aldeed** [comment]
Merged, thanks

**Comment by bySabi** [comment]
For `FixedHeader` extension you could do.

```html
<template name="filelist">
    {{> tabular table=TabularTables.Uploads id="user-files" class="table table-hover table-responsive"}}
</template>
```

```js
Template.filelist.rendered = function() {
  new $.fn.dataTable.FixedHeader( $('#user-files') );
};
```

**Comment by loiggeb** [comment]
Hi,

I was able to integrate TableTools and also Row Selection. Unfortunatly I am not able to create any kind of download. The swf File is stored in the public folder in the subfolder swf - the css and js files are stored in client/compatibility. 

That's my code so far:
````
TabularTables.HutchisonLinks = new Tabular.Table({
  name: "Hutchison Links",
  collection: HutchisonLinks,
  dom: 'T<"clear">lfrtip<"clear">R<"clear">C',
  tableTools: {
            "sRowSelect": "os",
            "aButtons": [ "copy", "csv", "pdf", "select_all", "select_none" ],
            "sSwfPath": "/swf/copy_csv_xls_pdf.swf"
  },
  responsive: true,
  columns: [
    {
      tmpl: Meteor.isClient && Template.linktodata
    },
    {data: "nummer", title: "Number"},
    {data: "standort_a", title: "Standort A"},
    {data: "standort_b", title: "Standort B"},
    {data: "linktype", title: "Linktype"},
  ]
});
````

**Comment by bloigge** [comment]
Fixed it by using this as my psSwfPath
''''
"sSwfPath": "http://dev.heco.de/datatables/frontend/js/TableTools-2.2.3/swf/copy_csv_xls_pdf.swf"
''''

No clue why it is not working with a local file.
