### ISSUE TITLE
Use responsive table with tabular

### ISSUE THREAD

**Issue by patrickleet** [aldeed/meteor-tabular#83]
http://getbootstrap.com/css/#tables-responsive

What's the best way to use responsive tables with tabular?
Adding .table-responsive to the col-xs-12 that the table is rendered in is all that is needed. I could do this with jQuery when rendered, but didn't know if there is a better supported way?

**Comment by patrickleet** [comment]
```javascript
Template.Items.rendered = function () {
  this.$('table').parent().addClass('table-responsive');
};
```

**Comment by aldeed** [comment]
Doesn't it work to do it directly in the HTML?

```html
<div class="table-responsive">
  {{> tabular table=TabularTables.Books class="table table-striped table-bordered table-condensed"}}
</div>
```

**Comment by yuomtheara** [comment]
should be fill it `{{> ..... class=" ........ table-responsive"}}` .

**Comment by patrickleet** [comment]
Thanks guys! I thought it had to be the direct parent element for some reason.
