### ISSUE TITLE
Provide extra cell template data

### ISSUE THREAD

**Issue by jrmurad** [aldeed/meteor-tabular#88]
I found myself wanting to use common templates which needed parameters from TabularTables. I coudn't use tmpl because the only data/context available to it is whatever was being subscribed to. I thought I'd share my solution of tapping into the internal *createdCell* while requesting that a more "correct" approach be supported if I'm not already missing out on a better way.

I wanted a column with a delete button. Many of my tables use a button like this with only a *queueName* variable (which is a property of the collection, not of any document) to differentiate them. I also had to use the undocumented/internal *orderable* key, otherwise the sort buttons would display:

    {
      createdCell: Meteor.isClient && function (cell, cellData, rowData) {
        return Blaze.renderWithData(Template.deleteButton, {
          queueName: queueName,
          _id: rowData._id
        }, cell);
      },
      width: '15px',
      orderable: false
    }

Another common column is for the "name" but to be a link. Rather than making a { tmpl: Template.someLink } for every kind of table I made a shared Template.nameLink which only needs the (Iron) Route name as a parameter. I had to override the render function so the value from data isn't rendered:

    {
      data: 'name',
      title: 'Name',
      createdCell: Meteor.isClient && function (cell, cellData, rowData) {
        return Blaze.renderWithData(Template.nameLink, {
          route: route,
          _id: rowData._id,
          slug: rowData.slug,
          name: rowData.name
        }, cell);
      },
      render: function () {}
    }

**Comment by aldeed** [comment]
This solution is probably fine. Depending on the exact situation, it might be easier to just have the data you need in an ancestor context, and then use `Template.parentData()` or `../` in your cell templates to access it. If the templates are generic, you could have a table-specific wrapper template. But that's about the same effect as using createdCell.

As for some better way, I suppose the table could take an `extraCellData` attribute which you set to an object that we then merge into the template context.

**Comment by bySabi** [comment]
Hi @jrmurad  and @aldeed I have a similar setup but not work at all.
Let´s explaind with code.

First: tabular settings `uploads.js` and template `fileList.html`

-----------------------
uploads.js
```
TabularTables = {};

Meteor.isClient && Template.registerHelper('TabularTables', TabularTables);

TabularTables.Uploads = new Tabular.Table({
  name: "Uploads",
  collection: Uploads.files,
  ordering: false,
  searching: false,
  info: false,
  //  paging: false, // is a bug here?: https://github.com/aldeed/meteor-tabular/issues/76
  columns: [
    {data: "name()", title: "Nombre"},    // FS.File.name()
    {data: "size()", title: "Tamaño"},
    {data: "type()", title: "Tipo"},
    {data: "updatedAt()", title: "Subido"},

//    {tmpl: Meteor.isClient && Template.fileListTools}
    {
      createdCell: Meteor.isClient && function (cell, cellData, rowData) {
        return Blaze.renderWithData(Template.fileListTools, {
          isSelected: false
        }, cell);
      },
      width: '15px',
      orderable: false
    }
  ]
});
```
------------------------------
fileList.html
```
<template name="filelist">
    {{> tabular table=TabularTables.Uploads class="table table-hover table-condensed"}}
</template>
````
Second: tabular template event handler
---------------------------
fileList.js
```
Session.setDefault('selectedfileListRow',null);

Template.filelist.events({
  'click tbody > tr': function (event) {
      /*
        table
          tr
            td
            td
      */
      var _td = $(event.target);
      var _tr = _td.closest('tr');
      var _table = _td.closest('table');

      var dataTable = _table.DataTable();
      var rowData = dataTable.row(event.currentTarget).data(); // rowData is a FS.File
      // select and deselect row's
      if ( $(_tr).hasClass('selected') ) {
        $(_tr).removeClass('selected');
        Session.set('selectedfileListRow',null);
      }
      else {
        // for access to dataTable API (include jQuery $())
        // _table.dataTable().api().$('tr.selected').removeClass('selected'); // find selected `tr`
        $(_table).find('tr.selected').removeClass('selected'); // find selected `tr`
        $(_tr).addClass('selected'); //current `tr
        Session.set('selectedfileListRow',_tr.index());
    }
  }
});
Template.filelist.rendered = function(){
  //a hacky hide cause paging:false option not work
  this.firstNode.children[0].children[0].hidden = true;
  this.firstNode.children[0].children[2].hidden = true;
}
```

Finally: semiworking code.
-----------------
fileListTools.html
```
<template name="fileListTools">
  <div>
    <div>
        {{#if isSelected}}
            BUTTONS
        {{/if}}
    </div>
  </div>
</template>
```
and template callbacks and helpers
------------------
```
Template.fileListTools.created = function(){
  this.showMe = new ReactiveVar;
  this.showMe.set(false);
};

Template.fileListTools.rendered = function(){
  var currentRow = $(this.firstNode.closest('tr')).index();
  var self = this;
  this.autorun(function() {
    if (Session.equals('selectedfileListRow', currentRow)) {
      self.showMe.set(true);
    } else {
      self.showMe.set(false);
    }
  });
};

Template.fileListTools.helpers({
  isSelected: function() {
    return Template.instance().showMe.get();
  }
});
```


`fileListTools` template must show buttons only on cell of selected table row. But, for example is you click another route and back latest selected row still show BUTTONS. I´m stuck here.

Is another recommeded way to implement this pattern of show/hide buttons on meteor with DataTable ?

**Comment by JimHough** [comment]
I also struggled with this problem.
I needed to access the data for the column that the template was used in but only had access to the whole document. I also wanted to know what collection the data came from. I tried adding the template manually in a render function and setting the context to a new object ```{collection:colName, columnVal:val, document:doc}```. This appeared to work OK but events from the buttons in the template didn't get captured by the templates event handlers. I think this was because I was using the Blaze.toHtml function which strips out the templates 'intelligence'.
I settled with adding to the doc object in the render function with a field name different enough for it not to clash with any existing:
```javascript
columns:[
	{title:'Info', data:'InfoTxt', tmpl:Meteor.isClient && Template.tabularLink,
		render: function(val, type, doc){
			doc.tabularCollectionName = 'tasks';
			doc.tabularColumnVal = val;
		}
	}
]
```

**Comment by shactdeveloper** [comment]
Hello, im facing the same problem. I need to create cells with links that use data from related collections
im using a helper to get the related collection info and implemeting like this:
```
    {data: "company()", title: "Company",
      createdCell: Meteor.isClient && function (cell, cellData, rowData) {
        return Blaze.renderWithData(Template.nameLink, {
          route: "company.view",
          _id: cellData._id,
          name: cellData.name
        }, cell);
      }, render: function(){}
    },
```


And my helper:

```
Costumer.helpers({
  company: function(){
    return Companies.findOne({_id:this.companyId});
  }
});
```


Is it the best solution ? it's polluting my code a lot =(

**Comment by aldeed** [comment]
This will be fixed in the next release. Here is excerpt from updated readme:

In your template and helpers, `this` is set to the document for the current row by default. If you need more information in your template context, such as which column it is for a shared template, you can set `tmplContext` to a function which takes the row data as an argument and returns the context, like this:

```js
{
  data: 'title',
  title: "Title",
  tmpl: Meteor.isClient && Template.sharedTemplate,
  tmplContext: function (rowData) {
    return {
      item: rowData,
      column: 'title'
    };
  }
}
```
