### ISSUE TITLE
Problem with deep properties when using collection helpers

### ISSUE THREAD

**Issue by serkandurusoy** [aldeed/meteor-tabular#89]
Collection helpers allow chaining of helpers. I can do this:

```
book.author().fullName()
```

So if we list books with a tabular table and ask for data like

```
data: 'author().fullName()'
```

We get back an error in the browser console (and no data rendered on table)

```
Exception from Tracker recompute function: Cannot read property 'fullName' of undefined
TypeError: Cannot read property 'fullName' of undefined
```

**Comment by aldeed** [comment]
I'm not sure if this can be fixed in the package because DataTables library handles this feature. But the docs do lead me to believe that your example should work. See the description of the "string type" here: http://datatables.net/reference/option/columns.data

**Comment by aldeed** [comment]
Although if the auther is simply not defined, I guess that would cause this. Apparently datatables isn't smart enough to ignore it.

Also make sure you're publishing all the related collections that the helpers rely on. They would either need to be published separately or you'd need to supply your own publish function for the table.

**Comment by serkandurusoy** [comment]
Unfortunately it somehow does not work within `data` but it does work within `render` so I'll be using that for now.

I'm using reywood:publish-composite and since it works with `render` I know the data is there.

So I guess I'll need to close this since this is datatables related.

Thanks for looking into it.

PS: +1 for all the client-side sort/filter request out there ;)
