### ISSUE TITLE
Table on Meteor.user - search not working

### ISSUE THREAD

**Issue by gerwinbrunner** [aldeed/meteor-tabular#9]
Hi,

I have the following table:

```
if (!this.TabularTables) {
  this.TabularTables = {};
}

Meteor.isClient && Template.registerHelper("TabularTables", TabularTables);

TabularTables.Users = new Tabular.Table({
  name: "Users",
  collection: Meteor.users,
  columns: [
    {
      data: "createdAt",
      title: "CreatedAt"
    }, {
      data: "profile.firstName",
      title: "firstName"
    }, {
      data: "profile.lastName",
      title: "lastName"
    }
  ]
});
```

The table works awesomely fast, but as soon as I type something into the search field nothing is displayed any more.

Do you have any idea what the reason for this could be?

Cheers,
Gerwin

**Comment by jasonshouse** [comment]
I'm experiencing the same issue on my site. If any columns have a property attached to the data object, then they are not searchable. For example:

{
     id: '1q2w3e4r5t6y',
     name: {
          first: 'Jon',
          last: 'Snow'
}

The id is searchable but the first and last names are not. I've tried commenting out some of cleanFieldName, which DID work - however the server keeps overwriting the file when I restart! :/

**Comment by aldeed** [comment]
I'm trying to finish up a rewrite that will address this and all other outstanding issues.

**Comment by jfols** [comment]
@aldeed Looking forward to this feature working :smile: Let me know if you need help testing any code

**Comment by aldeed** [comment]
1.0 is released and should fix this. Please see updated [README](https://github.com/aldeed/meteor-tabular/blob/master/README.md) for all features and options.

**Comment by jfols** [comment]
@aldeed woot! :metal:
