### ISSUE TITLE
Error thrown if namespace is not exactly TabularTables

### ISSUE THREAD

**Issue by serkandurusoy** [aldeed/meteor-tabular#91]
This is very interesting and I may be missing something, somewhere, but, unless the namespace is TabularTables, an error is thrown:

    You must pass Tabular.Table instance as the table attribute

So basically I cannot do this:

````javascript
Tables={}

if (Meteor.isClient) {
  Template.registerHelper('TabularTables', Tables);
}

{{> tabular table=Tables.myTable}}

Tables.myTable = new Tabular.Table({
  name: 'myTable',
  /* table props */
});
````

And it works again if I find/replace `Tables` to `TabularTables`

**Comment by aldeed** [comment]
Actually, I think this is a quirk of templating/blaze/spacebars (not sure which one exactly). I've run into it before. It's because helpers are called with a different `this` value, so it sort of overrides the prototype.

The solution is to do something like:

```js
Template.registerHelper('Tables', {
  myTable: Tables.myTable
});
```

Or if that doesn't work, then:

```js
Template.registerHelper('Tables', {
  myTable: function () {
    return Tables.myTable;
  }
});
```

**Comment by serkandurusoy** [comment]
Oh, I see. Well better keep it as it is than mess around with quirks ;)

In fact, I was thinking of suggesting you put the namespacing and initialization code right in the package and make it by default mandatory to create tables using the TabularTable namespace.

But, thanks for taking the time and explaining this.

**Comment by aldeed** [comment]
Interesting idea. I created #92 to track it.

**Comment by tetiolaw** [comment]
That's really strange, I've the same error in the following case:
- root
|->common
|->subfolder
------|->client
------|->common
------|->server

If I put the example shown in the readme in the root/subfolder/common it says  
You must pass Tabular.Table instance as the table attribute
If I put it in the root/common it works.

**Comment by tetiolaw** [comment]
That's really strange, I've the same error in the following case:
- root
|->common
|->subfolder
------|->client
------|->common
------|->server

If I put the example shown in the readme in the root/subfolder/common it says  
You must pass Tabular.Table instance as the table attribute
If I put it in the root/common it works.

**Comment by antarexis** [comment]
@aldeed I've noticed the same behavior as @tetiolaw . Is this normal? Should the we always put the file in /common and by no means in /common/subfolder?

STRANGE!

**Comment by djclarkson** [comment]
Have the same issue.

**Comment by aldeed** [comment]
Meteor loads the deepest nested files first, so if it's used in a deeply nested file but defined in a shallow nested file, it's used before it's defined and that won't work. There are various ways to solve. You could put table definitions in /lib, reconfigure the nesting, whatever is necessary so that the code is combined in the correct order.

**Comment by jdnichollsc** [comment]
@aldeed any example on GitHub using Meteor 1.3 to check that please?

**Comment by philcruz** [comment]
I'm using Meteor 1.3 and can't seem to get around this issue either.

**Comment by philcruz** [comment]
I did 

```

var myTable = new Tabular.Table({
	name: "Locations",
	collection: Markers,
	columns: [
		{data: "name", title: "Name"}
	]
});

Template.registerHelper('Tables', {
  myTable: myTable
});

```

and then changed the template to do 

`{{> tabular table=Tables.myTable class="table table-striped table-bordered table-condensed"}}`

and it worked. Not exactly clear that's what you need to do from reading the readme but it's working so I'm good to go.

**Comment by philcruz** [comment]
I did 

```

var myTable = new Tabular.Table({
	name: "Locations",
	collection: Markers,
	columns: [
		{data: "name", title: "Name"}
	]
});

Template.registerHelper('Tables', {
  myTable: myTable
});

```

and then changed the template to do 

`{{> tabular table=Tables.myTable class="table table-striped table-bordered table-condensed"}}`

and it worked. Not exactly clear that's what you need to do from reading the readme but I'm good.

**Comment by philcruz** [comment]
I did 

```

var myTable = new Tabular.Table({
	name: "Locations",
	collection: Markers,
	columns: [
		{data: "name", title: "Name"}
	]
});

Template.registerHelper('Tables', {
  myTable: myTable
});

```

and then changed the template to do 

`{{> tabular table=Tables.myTable class="table table-striped table-bordered table-condensed"}}`

and it worked. Not exactly clear that's what you need to do from reading the readme but I'm good.

**Comment by jdnichollsc** [comment]
Maybe a Pull request to include your example into the README? 👍
