### ISSUE TITLE
Register template helpers on the client

### ISSUE THREAD

**Issue by aldeed** [aldeed/meteor-tabular#92]
As a small time saver, the package could register template helper in client code in the `Tabular.Table` constructor. Something like:

```js
Template.registerHelper('TabularTables.' + name, function () {
  return self;
});
```

**Comment by serkandurusoy** [comment]
:+1:  we're not trying to rename SimpleSchema so why should we want to rename TabularTables anyway. Also cleaner and less error prone.

**Comment by aldeed** [comment]
Done in next release
