### ISSUE TITLE
Question: how to publish depending on another collection

### ISSUE THREAD

**Issue by serkandurusoy** [aldeed/meteor-tabular#95]
I'm trying to display a datatable from a collection with a criteria that is dependant on another collection, namely, I'm querying the second collection to get back a list of ids as a primary criteria to the table's selector. So I've got something like this:

````javascript
TabularTables.myTable = new Tabular.Table({
  selector: function(userId) {
    return {
      _id: {
        $in: OtherCollection.find({
          userA: userId,
          userB: {$ne: userId}
        }).map(function(item) {
          return item.foreignKey;
        })
      },
      user: {$ne: userId},
      someOtherCriteria: xxx'
    };
  },
  {/* other table props, columns etc */}
````

No this works if I change something on the table, like paging, number of items on page, filter, sorting etc. But does not reactively update when a new relevant document is inserted.

I've tried putting the selector function within a `Tracker.autorun` block, but that obviously did not help either.

As a side note, I'm publishing the table data using `publish-composite` and also in another publication, I'm sending relevant `OtherCollection` documents, and I know that they are present on the client.

So, how do I attack this problem?

Thanks.

PS: I keep myself asking questions here instead of stackoverflow, but I feel it is more appropriate and relevant asking them here in context. Let me know if you think otherwise.

**Comment by aldeed** [comment]
If the relevant othercollection docs are on the client already, then you can use the client side selector instead, which will then be reactive.

**Comment by aldeed** [comment]
Or include the same OtherCollection.find call in your table publication, which should set up the proper observes to make it reactive.

**Comment by serkandurusoy** [comment]
The problem with the publication is, the fin call for the othercollection needs to come first and also it has constraints for the _id which needs to be merged with the `ids` tabular provides. And that causes problems.

I guess I'll go with a client selector.

Thanks.
